// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { DucElement } from '../duc/duc-element';
import { DucGroup } from '../duc/duc-group';


export class AppState {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AppState {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAppState(bb:flatbuffers.ByteBuffer, obj?:AppState):AppState {
  return (obj || new AppState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAppState(bb:flatbuffers.ByteBuffer, obj?:AppState):AppState {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AppState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

isLoading():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

activeEmbeddableElement(obj?:DucElement):DucElement|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new DucElement()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

activeEmbeddableState():string|null
activeEmbeddableState(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
activeEmbeddableState(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

draggingElement(obj?:DucElement):DucElement|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new DucElement()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

resizingElement(obj?:DucElement):DucElement|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new DucElement()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

multiElement(obj?:DucElement):DucElement|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new DucElement()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

selectionElement(obj?:DucElement):DucElement|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? (obj || new DucElement()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

frameToHighlight(obj?:DucElement):DucElement|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? (obj || new DucElement()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

frameRenderingEnabled():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

frameRenderingName():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

frameRenderingOutline():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

frameRenderingClip():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

editingFrame():string|null
editingFrame(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
editingFrame(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

elementsToHighlight(index: number, obj?:DucElement):DucElement|null {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? (obj || new DucElement()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

elementsToHighlightLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

editingElement(obj?:DucElement):DucElement|null {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? (obj || new DucElement()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

currentItemStrokeColor():string|null
currentItemStrokeColor(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
currentItemStrokeColor(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 34);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

currentItemBackgroundColor():string|null
currentItemBackgroundColor(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
currentItemBackgroundColor(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 36);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

currentItemFillStyle():string|null
currentItemFillStyle(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
currentItemFillStyle(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 38);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

currentItemStrokeWidth():number {
  const offset = this.bb!.__offset(this.bb_pos, 40);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

currentItemStrokeStyle():string|null
currentItemStrokeStyle(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
currentItemStrokeStyle(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 42);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

currentItemRoughness():number {
  const offset = this.bb!.__offset(this.bb_pos, 44);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

currentItemOpacity():number {
  const offset = this.bb!.__offset(this.bb_pos, 46);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

currentItemFontFamily():string|null
currentItemFontFamily(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
currentItemFontFamily(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 48);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

currentItemFontSize():number {
  const offset = this.bb!.__offset(this.bb_pos, 50);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

currentItemTextAlign():string|null
currentItemTextAlign(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
currentItemTextAlign(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 52);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

currentItemStartArrowhead():string|null
currentItemStartArrowhead(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
currentItemStartArrowhead(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 54);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

currentItemEndArrowhead():string|null
currentItemEndArrowhead(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
currentItemEndArrowhead(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 56);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

currentItemRoundness():string|null
currentItemRoundness(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
currentItemRoundness(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 58);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

viewBackgroundColor():string|null
viewBackgroundColor(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
viewBackgroundColor(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 60);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

scope():string|null
scope(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
scope(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 62);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

writingLayer():string|null
writingLayer(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
writingLayer(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 64);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

groups(index: number, obj?:DucGroup):DucGroup|null {
  const offset = this.bb!.__offset(this.bb_pos, 66);
  return offset ? (obj || new DucGroup()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

groupsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 66);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

scrollX():number {
  const offset = this.bb!.__offset(this.bb_pos, 68);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

scrollY():number {
  const offset = this.bb!.__offset(this.bb_pos, 70);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

cursorButton():string|null
cursorButton(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
cursorButton(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 72);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

scrolledOutside():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 74);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 76);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

isResizing():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 78);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

isRotating():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 80);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

zoom():number {
  const offset = this.bb!.__offset(this.bb_pos, 82);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

lastPointerDownWith():string|null
lastPointerDownWith(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
lastPointerDownWith(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 84);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

selectedElementIds(index: number):string
selectedElementIds(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
selectedElementIds(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 86);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

selectedElementIdsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 86);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

previousSelectedElementIds(index: number):string
previousSelectedElementIds(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
previousSelectedElementIds(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 88);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

previousSelectedElementIdsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 88);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

selectedElementsAreBeingDragged():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 90);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

shouldCacheIgnoreZoom():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 92);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

gridSize():number {
  const offset = this.bb!.__offset(this.bb_pos, 94);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

selectedGroupIds(index: number):string
selectedGroupIds(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
selectedGroupIds(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 96);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

selectedGroupIdsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 96);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

editingGroupId():string|null
editingGroupId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
editingGroupId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 98);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

width():number {
  const offset = this.bb!.__offset(this.bb_pos, 100);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

height():number {
  const offset = this.bb!.__offset(this.bb_pos, 102);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

offsetTop():number {
  const offset = this.bb!.__offset(this.bb_pos, 104);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

offsetLeft():number {
  const offset = this.bb!.__offset(this.bb_pos, 106);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

pasteDialogShown():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 108);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

pasteDialogData():string|null
pasteDialogData(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
pasteDialogData(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 110);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

pendingImageElementId():string|null
pendingImageElementId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
pendingImageElementId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 112);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

originSnapOffsetX():number {
  const offset = this.bb!.__offset(this.bb_pos, 114);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

originSnapOffsetY():number {
  const offset = this.bb!.__offset(this.bb_pos, 116);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

scaleRatioLocked():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 118);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

displayAllPointDistances():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 120);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

displayDistanceOnDrawing():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 122);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

enableLineBendingOnEdit():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 124);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

allowIndependentCurveHandles():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 126);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

coordDecimalPlaces():number {
  const offset = this.bb!.__offset(this.bb_pos, 128);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startAppState(builder:flatbuffers.Builder) {
  builder.startObject(63);
}

static addIsLoading(builder:flatbuffers.Builder, isLoading:boolean) {
  builder.addFieldInt8(0, +isLoading, +false);
}

static addActiveEmbeddableElement(builder:flatbuffers.Builder, activeEmbeddableElementOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, activeEmbeddableElementOffset, 0);
}

static addActiveEmbeddableState(builder:flatbuffers.Builder, activeEmbeddableStateOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, activeEmbeddableStateOffset, 0);
}

static addDraggingElement(builder:flatbuffers.Builder, draggingElementOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, draggingElementOffset, 0);
}

static addResizingElement(builder:flatbuffers.Builder, resizingElementOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, resizingElementOffset, 0);
}

static addMultiElement(builder:flatbuffers.Builder, multiElementOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, multiElementOffset, 0);
}

static addSelectionElement(builder:flatbuffers.Builder, selectionElementOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, selectionElementOffset, 0);
}

static addFrameToHighlight(builder:flatbuffers.Builder, frameToHighlightOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, frameToHighlightOffset, 0);
}

static addFrameRenderingEnabled(builder:flatbuffers.Builder, frameRenderingEnabled:boolean) {
  builder.addFieldInt8(8, +frameRenderingEnabled, +false);
}

static addFrameRenderingName(builder:flatbuffers.Builder, frameRenderingName:boolean) {
  builder.addFieldInt8(9, +frameRenderingName, +false);
}

static addFrameRenderingOutline(builder:flatbuffers.Builder, frameRenderingOutline:boolean) {
  builder.addFieldInt8(10, +frameRenderingOutline, +false);
}

static addFrameRenderingClip(builder:flatbuffers.Builder, frameRenderingClip:boolean) {
  builder.addFieldInt8(11, +frameRenderingClip, +false);
}

static addEditingFrame(builder:flatbuffers.Builder, editingFrameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(12, editingFrameOffset, 0);
}

static addElementsToHighlight(builder:flatbuffers.Builder, elementsToHighlightOffset:flatbuffers.Offset) {
  builder.addFieldOffset(13, elementsToHighlightOffset, 0);
}

static createElementsToHighlightVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startElementsToHighlightVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addEditingElement(builder:flatbuffers.Builder, editingElementOffset:flatbuffers.Offset) {
  builder.addFieldOffset(14, editingElementOffset, 0);
}

static addCurrentItemStrokeColor(builder:flatbuffers.Builder, currentItemStrokeColorOffset:flatbuffers.Offset) {
  builder.addFieldOffset(15, currentItemStrokeColorOffset, 0);
}

static addCurrentItemBackgroundColor(builder:flatbuffers.Builder, currentItemBackgroundColorOffset:flatbuffers.Offset) {
  builder.addFieldOffset(16, currentItemBackgroundColorOffset, 0);
}

static addCurrentItemFillStyle(builder:flatbuffers.Builder, currentItemFillStyleOffset:flatbuffers.Offset) {
  builder.addFieldOffset(17, currentItemFillStyleOffset, 0);
}

static addCurrentItemStrokeWidth(builder:flatbuffers.Builder, currentItemStrokeWidth:number) {
  builder.addFieldInt32(18, currentItemStrokeWidth, 0);
}

static addCurrentItemStrokeStyle(builder:flatbuffers.Builder, currentItemStrokeStyleOffset:flatbuffers.Offset) {
  builder.addFieldOffset(19, currentItemStrokeStyleOffset, 0);
}

static addCurrentItemRoughness(builder:flatbuffers.Builder, currentItemRoughness:number) {
  builder.addFieldInt32(20, currentItemRoughness, 0);
}

static addCurrentItemOpacity(builder:flatbuffers.Builder, currentItemOpacity:number) {
  builder.addFieldFloat32(21, currentItemOpacity, 0.0);
}

static addCurrentItemFontFamily(builder:flatbuffers.Builder, currentItemFontFamilyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(22, currentItemFontFamilyOffset, 0);
}

static addCurrentItemFontSize(builder:flatbuffers.Builder, currentItemFontSize:number) {
  builder.addFieldInt32(23, currentItemFontSize, 0);
}

static addCurrentItemTextAlign(builder:flatbuffers.Builder, currentItemTextAlignOffset:flatbuffers.Offset) {
  builder.addFieldOffset(24, currentItemTextAlignOffset, 0);
}

static addCurrentItemStartArrowhead(builder:flatbuffers.Builder, currentItemStartArrowheadOffset:flatbuffers.Offset) {
  builder.addFieldOffset(25, currentItemStartArrowheadOffset, 0);
}

static addCurrentItemEndArrowhead(builder:flatbuffers.Builder, currentItemEndArrowheadOffset:flatbuffers.Offset) {
  builder.addFieldOffset(26, currentItemEndArrowheadOffset, 0);
}

static addCurrentItemRoundness(builder:flatbuffers.Builder, currentItemRoundnessOffset:flatbuffers.Offset) {
  builder.addFieldOffset(27, currentItemRoundnessOffset, 0);
}

static addViewBackgroundColor(builder:flatbuffers.Builder, viewBackgroundColorOffset:flatbuffers.Offset) {
  builder.addFieldOffset(28, viewBackgroundColorOffset, 0);
}

static addScope(builder:flatbuffers.Builder, scopeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(29, scopeOffset, 0);
}

static addWritingLayer(builder:flatbuffers.Builder, writingLayerOffset:flatbuffers.Offset) {
  builder.addFieldOffset(30, writingLayerOffset, 0);
}

static addGroups(builder:flatbuffers.Builder, groupsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(31, groupsOffset, 0);
}

static createGroupsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startGroupsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addScrollX(builder:flatbuffers.Builder, scrollX:number) {
  builder.addFieldFloat32(32, scrollX, 0.0);
}

static addScrollY(builder:flatbuffers.Builder, scrollY:number) {
  builder.addFieldFloat32(33, scrollY, 0.0);
}

static addCursorButton(builder:flatbuffers.Builder, cursorButtonOffset:flatbuffers.Offset) {
  builder.addFieldOffset(34, cursorButtonOffset, 0);
}

static addScrolledOutside(builder:flatbuffers.Builder, scrolledOutside:boolean) {
  builder.addFieldInt8(35, +scrolledOutside, +false);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(36, nameOffset, 0);
}

static addIsResizing(builder:flatbuffers.Builder, isResizing:boolean) {
  builder.addFieldInt8(37, +isResizing, +false);
}

static addIsRotating(builder:flatbuffers.Builder, isRotating:boolean) {
  builder.addFieldInt8(38, +isRotating, +false);
}

static addZoom(builder:flatbuffers.Builder, zoom:number) {
  builder.addFieldFloat32(39, zoom, 0.0);
}

static addLastPointerDownWith(builder:flatbuffers.Builder, lastPointerDownWithOffset:flatbuffers.Offset) {
  builder.addFieldOffset(40, lastPointerDownWithOffset, 0);
}

static addSelectedElementIds(builder:flatbuffers.Builder, selectedElementIdsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(41, selectedElementIdsOffset, 0);
}

static createSelectedElementIdsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startSelectedElementIdsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addPreviousSelectedElementIds(builder:flatbuffers.Builder, previousSelectedElementIdsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(42, previousSelectedElementIdsOffset, 0);
}

static createPreviousSelectedElementIdsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startPreviousSelectedElementIdsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addSelectedElementsAreBeingDragged(builder:flatbuffers.Builder, selectedElementsAreBeingDragged:boolean) {
  builder.addFieldInt8(43, +selectedElementsAreBeingDragged, +false);
}

static addShouldCacheIgnoreZoom(builder:flatbuffers.Builder, shouldCacheIgnoreZoom:boolean) {
  builder.addFieldInt8(44, +shouldCacheIgnoreZoom, +false);
}

static addGridSize(builder:flatbuffers.Builder, gridSize:number) {
  builder.addFieldInt32(45, gridSize, 0);
}

static addSelectedGroupIds(builder:flatbuffers.Builder, selectedGroupIdsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(46, selectedGroupIdsOffset, 0);
}

static createSelectedGroupIdsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startSelectedGroupIdsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addEditingGroupId(builder:flatbuffers.Builder, editingGroupIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(47, editingGroupIdOffset, 0);
}

static addWidth(builder:flatbuffers.Builder, width:number) {
  builder.addFieldInt32(48, width, 0);
}

static addHeight(builder:flatbuffers.Builder, height:number) {
  builder.addFieldInt32(49, height, 0);
}

static addOffsetTop(builder:flatbuffers.Builder, offsetTop:number) {
  builder.addFieldInt32(50, offsetTop, 0);
}

static addOffsetLeft(builder:flatbuffers.Builder, offsetLeft:number) {
  builder.addFieldInt32(51, offsetLeft, 0);
}

static addPasteDialogShown(builder:flatbuffers.Builder, pasteDialogShown:boolean) {
  builder.addFieldInt8(52, +pasteDialogShown, +false);
}

static addPasteDialogData(builder:flatbuffers.Builder, pasteDialogDataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(53, pasteDialogDataOffset, 0);
}

static addPendingImageElementId(builder:flatbuffers.Builder, pendingImageElementIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(54, pendingImageElementIdOffset, 0);
}

static addOriginSnapOffsetX(builder:flatbuffers.Builder, originSnapOffsetX:number) {
  builder.addFieldFloat32(55, originSnapOffsetX, 0.0);
}

static addOriginSnapOffsetY(builder:flatbuffers.Builder, originSnapOffsetY:number) {
  builder.addFieldFloat32(56, originSnapOffsetY, 0.0);
}

static addScaleRatioLocked(builder:flatbuffers.Builder, scaleRatioLocked:boolean) {
  builder.addFieldInt8(57, +scaleRatioLocked, +false);
}

static addDisplayAllPointDistances(builder:flatbuffers.Builder, displayAllPointDistances:boolean) {
  builder.addFieldInt8(58, +displayAllPointDistances, +false);
}

static addDisplayDistanceOnDrawing(builder:flatbuffers.Builder, displayDistanceOnDrawing:boolean) {
  builder.addFieldInt8(59, +displayDistanceOnDrawing, +false);
}

static addEnableLineBendingOnEdit(builder:flatbuffers.Builder, enableLineBendingOnEdit:boolean) {
  builder.addFieldInt8(60, +enableLineBendingOnEdit, +false);
}

static addAllowIndependentCurveHandles(builder:flatbuffers.Builder, allowIndependentCurveHandles:boolean) {
  builder.addFieldInt8(61, +allowIndependentCurveHandles, +false);
}

static addCoordDecimalPlaces(builder:flatbuffers.Builder, coordDecimalPlaces:number) {
  builder.addFieldInt32(62, coordDecimalPlaces, 0);
}

static endAppState(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
