export const GITHUB_URL = "https://github.com/ducflair/duc"
export const REDDIT_URL = "https://reddit.com/r/duc_"
export const FORUM_URL = "https://help.ducflair.com/c/duc"
export const PLAYGROUND_URL = "https://scopture.com"
export const MICROSCOPE_EXAMPLE_URL = "https://scopture.com/w/gR3TrgiTVTLuA98mgv"