[workspace]
resolver = "2"
members = [
    "packages/ducrs",
    "packages/ducjs/crate",
    "packages/ducpy/crate",
    "packages/ducpdf/src/duc2pdf",
    "packages/ducsvg/src/pdf2svg",
    "patches/sqlite-wasm-vfs",
]

[workspace.metadata.wasm-pack]
"wasm-pack" = "0.14.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = "s"
lto = true

[profile.release-small]
inherits = "release"
opt-level = "z"
codegen-units = 1
strip = true
panic = "abort"

[patch.crates-io]
sqlite-wasm-vfs = { path = "patches/sqlite-wasm-vfs" }
