//! Schema bootstrap — applies `schema/duc.sql` to a fresh connection.
//!
//! Called by both `native` and `wasm` backends after opening a connection.
//! The canonical schema lives at `duc.sql` in the workspace root; it is
//! embedded at compile time so the binary carries no file-system dependency.

use rusqlite::Connection;

use crate::db::DbError;

/// Canonical schemas, embedded at compile time.
/// `build.rs` copies them into `OUT_DIR` so this works both in-tree and from sdists.
/// Applied in order: duc.sql → version_control.sql → search.sql
const DUC_SCHEMA: &str = include_str!(concat!(env!("OUT_DIR"), "/duc.sql"));
const VERSION_CONTROL_SCHEMA: &str = include_str!(concat!(env!("OUT_DIR"), "/version_control.sql"));
const SEARCH_SCHEMA: &str = include_str!(concat!(env!("OUT_DIR"), "/search.sql"));

/// Expected `application_id` written by `duc.sql`.
const APP_ID: i64 = 1_146_569_567; // "DUC_" in ASCII

/// Schema version read from `duc.sql` at compile time by `build.rs`.
/// Never hardcode this — it is always in sync with the SQL file.
const CURRENT_VERSION: i64 = {
    // build.rs emits DUC_SCHEMA_USER_VERSION as a decimal integer string.
    let bytes = env!("DUC_SCHEMA_USER_VERSION").as_bytes();
    let mut val: i64 = 0;
    let mut i = 0;
    while i < bytes.len() {
        val = val * 10 + (bytes[i] - b'0') as i64;
        i += 1;
    }
    val
};

/// Runtime accessor for the compile-time schema version integer.
pub fn current_schema_version_int() -> i64 {
    CURRENT_VERSION
}

// Migration registry auto-generated by build.rs from `schema/migrations/*.sql`.
// Each entry is (from_version, to_version, sql). Sorted ascending by from_version.
include!(concat!(env!("OUT_DIR"), "/migrations_registry.rs"));

// ── Public re-exports for downstream crates ─────────────────────────────

/// Current schema version as a semver string (generated at build time).
pub const CURRENT_SCHEMA_VERSION_SEMVER: &str = env!("DUC_SCHEMA_VERSION");

pub const DUC_SCHEMA_SQL: &str = DUC_SCHEMA;
pub const VERSION_CONTROL_SCHEMA_SQL: &str = VERSION_CONTROL_SCHEMA;
pub const SEARCH_SCHEMA_SQL: &str = SEARCH_SCHEMA;

/// Per-connection PRAGMAs that must be re-applied on every open (they are
/// either ephemeral or take effect only after the first statement on the
/// connection).
#[cfg(not(all(target_family = "wasm", target_os = "unknown")))]
const CONN_PRAGMAS: &str = "
    PRAGMA journal_mode = WAL;
    PRAGMA foreign_keys  = ON;
";

#[cfg(all(target_family = "wasm", target_os = "unknown"))]
const CONN_PRAGMAS: &str = "
    PRAGMA journal_mode = MEMORY;
    PRAGMA foreign_keys  = ON;
";

/// Apply the full schema to `conn` if it is a new (empty) database, then
/// always re-apply the per-connection PRAGMAs.
///
/// Safe to call multiple times on an already-bootstrapped database — it
/// will only run the DDL once.
pub(crate) fn bootstrap(conn: &Connection) -> Result<(), DbError> {
    let user_version: i64 = conn.pragma_query_value(None, "user_version", |r| r.get(0))?;

    if user_version == 0 {
        // Apply schemas in order.
        conn.execute_batch(DUC_SCHEMA)
            .map_err(|e| DbError::Bootstrap(format!("duc.sql apply failed: {e}")))?;
        conn.execute_batch(VERSION_CONTROL_SCHEMA)
            .map_err(|e| DbError::Bootstrap(format!("version_control.sql apply failed: {e}")))?;
        conn.execute_batch(SEARCH_SCHEMA)
            .map_err(|e| DbError::Bootstrap(format!("search.sql apply failed: {e}")))?;

        // Verify the schema set the expected application_id.
        let app_id: i64 = conn.pragma_query_value(None, "application_id", |r| r.get(0))?;
        if app_id != APP_ID {
            return Err(DbError::Bootstrap(format!(
                "unexpected application_id after bootstrap: {app_id} (expected {APP_ID})"
            )));
        }
    } else if user_version == CURRENT_VERSION {
        // Current schema — just ensure per-connection pragmas are active.
        conn.execute_batch(CONN_PRAGMAS)
            .map_err(|e| DbError::Bootstrap(format!("pragma apply failed: {e}")))?;
    } else {
        // Older database: normalize any known schema drift before running the
        // canonical migration chain. Fixtures written by prerelease code may
        // have applied parts of later schemas without bumping user_version, so
        // we add columns/indexes migrations expect when missing and recreate
        // objects that already exist to keep the migration SQL idempotent.
        conn.execute_batch("SAVEPOINT duc_legacy_normalization")
            .map_err(|e| DbError::Bootstrap(format!("legacy normalization begin failed: {e}")))?;
        if let Err(error) = normalize_legacy_schema(conn, user_version) {
            let _ = conn.execute_batch(
                "ROLLBACK TO duc_legacy_normalization;
                 RELEASE duc_legacy_normalization;",
            );
            return Err(error);
        }
        conn.execute_batch("RELEASE duc_legacy_normalization")
            .map_err(|e| DbError::Bootstrap(format!("legacy normalization commit failed: {e}")))?;

        // Walk the migration chain until we reach CURRENT_VERSION.
        // build.rs generates MIGRATIONS sorted by from_version, so chaining
        // (e.g. 3000000→3000001→3000002) works without any code changes here.
        let mut current = user_version;
        loop {
            match MIGRATIONS.iter().find(|(from, _, _)| *from == current) {
                Some((from, to, sql)) => {
                    if let Err(error) = conn.execute_batch(sql) {
                        let _ = conn.execute_batch("ROLLBACK");
                        return Err(DbError::Bootstrap(format!(
                            "migration {from}\u{2192}{to} failed: {error}"
                        )));
                    }
                    // Re-read the version the migration SQL set via PRAGMA user_version.
                    current = conn.pragma_query_value(None, "user_version", |r| r.get(0))?;
                    if current == CURRENT_VERSION {
                        break;
                    }
                }
                None => {
                    return Err(DbError::Bootstrap(format!(
                        "unsupported schema version {user_version}; expected 0 or {CURRENT_VERSION}"
                    )));
                }
            }
        }
        conn.execute_batch(CONN_PRAGMAS)
            .map_err(|e| DbError::Bootstrap(format!("pragma apply failed: {e}")))?;
    }

    Ok(())
}

/// Add missing columns/objects that later migrations expect.
///
/// Some test fixtures were produced by intermediate code that created tables
/// such as `search_elements` or renamed `element_model.svg_path` to `thumbnail`
/// while still reporting an older `user_version`. Adding the missing legacy
/// columns back lets the canonical migration SQL run without modification.
fn normalize_legacy_schema(conn: &Connection, user_version: i64) -> Result<(), DbError> {
    if user_version <= 3000001 {
        normalize_external_revision_storage(conn)?;
    }

    // 3000003→3000004 migration expects `element_model.svg_path`.
    if user_version <= 3000004 {
        let has_column: bool = conn
            .query_row(
                "SELECT 1 FROM pragma_table_info('element_model') WHERE name = 'svg_path'",
                [],
                |_| Ok(true),
            )
            .unwrap_or(false);
        if !has_column {
            conn.execute(
                "ALTER TABLE element_model ADD COLUMN svg_path TEXT DEFAULT NULL",
                [],
            )
            .map_err(|e| {
                DbError::Bootstrap(format!(
                    "legacy normalization: add element_model.svg_path failed: {e}"
                ))
            })?;
        }
    }

    Ok(())
}

fn normalize_external_revision_storage(conn: &Connection) -> Result<(), DbError> {
    let table_exists = |table: &str| -> rusqlite::Result<bool> {
        conn.query_row(
            "SELECT EXISTS(
                SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ?1
             )",
            [table],
            |row| row.get(0),
        )
    };
    let column_exists = |table: &str, column: &str| -> rusqlite::Result<bool> {
        conn.query_row(
            "SELECT EXISTS(
                SELECT 1 FROM pragma_table_info(?1) WHERE name = ?2
             )",
            [table, column],
            |row| row.get(0),
        )
    };

    if !table_exists("external_file_revisions")? {
        return Ok(());
    }

    if !column_exists("external_file_revisions", "data")? {
        conn.execute(
            "ALTER TABLE external_file_revisions ADD COLUMN data BLOB",
            [],
        )
        .map_err(|error| {
            DbError::Bootstrap(format!(
                "legacy normalization: add external_file_revisions.data failed: {error}"
            ))
        })?;
    }

    for source_table in [
        "_external_file_revision_data_v3000001",
        "external_file_revision_data",
    ] {
        if table_exists(source_table)? {
            let sql = format!(
                "UPDATE external_file_revisions
                 SET data = (
                     SELECT source.data FROM {source_table} AS source
                     WHERE source.revision_id = external_file_revisions.id
                 )
                 WHERE data IS NULL AND EXISTS (
                     SELECT 1 FROM {source_table} AS source
                     WHERE source.revision_id = external_file_revisions.id
                 )"
            );
            conn.execute(&sql, []).map_err(|error| {
                DbError::Bootstrap(format!(
                    "legacy normalization: restore revision data from {source_table} failed: {error}"
                ))
            })?;
        }
    }

    if table_exists("external_file_revision_chunks")? {
        let revision_ids = {
            let mut statement = conn
                .prepare(
                    "SELECT id FROM external_file_revisions
                     WHERE data IS NULL
                     ORDER BY id",
                )
                .map_err(|error| {
                    DbError::Bootstrap(format!(
                        "legacy normalization: list chunked revisions failed: {error}"
                    ))
                })?;
            let rows = statement
                .query_map([], |row| row.get::<_, String>(0))
                .map_err(|error| {
                    DbError::Bootstrap(format!(
                        "legacy normalization: query chunked revisions failed: {error}"
                    ))
                })?;
            rows.collect::<rusqlite::Result<Vec<_>>>()
                .map_err(|error| {
                    DbError::Bootstrap(format!(
                        "legacy normalization: read chunked revisions failed: {error}"
                    ))
                })?
        };

        for revision_id in revision_ids {
            let data = crate::external_file_chunks::read_revision_chunks(conn, &revision_id)
                .map_err(|error| {
                    DbError::Bootstrap(format!(
                        "legacy normalization: read chunks for revision {revision_id} failed: {error}"
                    ))
                })?;
            if !data.is_empty() {
                conn.execute(
                    "UPDATE external_file_revisions SET data = ?2 WHERE id = ?1",
                    rusqlite::params![revision_id, data],
                )
                .map_err(|error| {
                    DbError::Bootstrap(format!(
                        "legacy normalization: restore chunks for revision failed: {error}"
                    ))
                })?;
            }
        }
    }

    conn.execute(
        "UPDATE external_file_revisions
         SET data = X''
         WHERE data IS NULL AND size_bytes = 0",
        [],
    )?;
    let missing_data: i64 = conn.query_row(
        "SELECT count(*) FROM external_file_revisions
         WHERE data IS NULL",
        [],
        |row| row.get(0),
    )?;
    if missing_data > 0 {
        return Err(DbError::Bootstrap(format!(
            "legacy normalization: {missing_data} external file revisions have metadata but no recoverable data"
        )));
    }

    for table in [
        "external_file_revision_chunks",
        "external_file_revision_data",
        "_external_file_revision_data_v3000001",
    ] {
        if table_exists(table)? {
            conn.execute_batch(&format!("DROP TABLE {table}"))
                .map_err(|error| {
                    DbError::Bootstrap(format!(
                        "legacy normalization: drop superseded {table} failed: {error}"
                    ))
                })?;
        }
    }

    Ok(())
}

#[cfg(test)]
#[path = "bootstrap_tests.rs"]
mod tests;
