//! Schema bootstrap — applies `schema/duc.sql` to a fresh connection.
//!
//! Called by both `native` and `wasm` backends after opening a connection.
//! The canonical schema lives at `duc.sql` in the workspace root; it is
//! embedded at compile time so the binary carries no file-system dependency.

use rusqlite::{Connection, OptionalExtension};

use crate::db::DbError;

/// Canonical schemas, embedded at compile time.
/// `build.rs` copies them into `OUT_DIR` so this works both in-tree and from sdists.
/// Applied in order: duc.sql → version_control.sql → search.sql
const DUC_SCHEMA: &str = include_str!(concat!(env!("OUT_DIR"), "/duc.sql"));
const VERSION_CONTROL_SCHEMA: &str = include_str!(concat!(env!("OUT_DIR"), "/version_control.sql"));
const SEARCH_SCHEMA: &str = include_str!(concat!(env!("OUT_DIR"), "/search.sql"));

/// Expected `application_id` written by `duc.sql`.
const APP_ID: i64 = 1_146_569_567; // "DUC_" in ASCII

/// Schema version read from `duc.sql` at compile time by `build.rs`.
/// Never hardcode this — it is always in sync with the SQL file.
const CURRENT_VERSION: i64 = {
    // build.rs emits DUC_SCHEMA_USER_VERSION as a decimal integer string.
    let bytes = env!("DUC_SCHEMA_USER_VERSION").as_bytes();
    let mut val: i64 = 0;
    let mut i = 0;
    while i < bytes.len() {
        val = val * 10 + (bytes[i] - b'0') as i64;
        i += 1;
    }
    val
};

/// Runtime accessor for the compile-time schema version integer.
pub fn current_schema_version_int() -> i64 {
    CURRENT_VERSION
}

// Migration registry auto-generated by build.rs from `schema/migrations/*.sql`.
// Each entry is (from_version, to_version, sql). Sorted ascending by from_version.
include!(concat!(env!("OUT_DIR"), "/migrations_registry.rs"));

// ── Public re-exports for downstream crates ─────────────────────────────

/// Current schema version as a semver string (generated at build time).
pub const CURRENT_SCHEMA_VERSION_SEMVER: &str = env!("DUC_SCHEMA_VERSION");

pub const DUC_SCHEMA_SQL: &str = DUC_SCHEMA;
pub const VERSION_CONTROL_SCHEMA_SQL: &str = VERSION_CONTROL_SCHEMA;
pub const SEARCH_SCHEMA_SQL: &str = SEARCH_SCHEMA;

/// Per-connection PRAGMAs that must be re-applied on every open (they are
/// either ephemeral or take effect only after the first statement on the
/// connection).
#[cfg(not(all(target_family = "wasm", target_os = "unknown")))]
const CONN_PRAGMAS: &str = "
    PRAGMA journal_mode = WAL;
    PRAGMA foreign_keys  = ON;
    PRAGMA synchronous   = NORMAL;
";

#[cfg(all(target_family = "wasm", target_os = "unknown"))]
const CONN_PRAGMAS: &str = "
    PRAGMA journal_mode = MEMORY;
    PRAGMA foreign_keys  = ON;
    PRAGMA synchronous   = NORMAL;
";

/// Apply the full schema to `conn` if it is a new (empty) database, then
/// always re-apply the per-connection PRAGMAs.
///
/// Safe to call multiple times on an already-bootstrapped database — it
/// will only run the DDL once.
pub(crate) fn bootstrap(conn: &Connection) -> Result<(), DbError> {
    let user_version: i64 = conn.pragma_query_value(None, "user_version", |r| r.get(0))?;

    if user_version == 0 {
        bootstrap_fresh_database(conn)?;
    } else if user_version == CURRENT_VERSION {
        // Current schema — ensure per-connection pragmas are active and repair
        // legacy version graphs written without their referenced chain row.
        conn.execute_batch(CONN_PRAGMAS)
            .map_err(|e| DbError::Bootstrap(format!("pragma apply failed: {e}")))?;
        conn.execute_batch("SAVEPOINT duc_current_version_graph_normalization")
            .map_err(|error| {
                DbError::Bootstrap(format!(
                    "current version graph normalization begin failed: {error}"
                ))
            })?;
        if let Err(error) = normalize_legacy_version_graph(conn) {
            let _ = conn.execute_batch(
                "ROLLBACK TO duc_current_version_graph_normalization;
                 RELEASE duc_current_version_graph_normalization;",
            );
            return Err(error);
        }
        conn.execute_batch("RELEASE duc_current_version_graph_normalization")
            .map_err(|error| {
                DbError::Bootstrap(format!(
                    "current version graph normalization commit failed: {error}"
                ))
            })?;
    } else {
        validate_migration_path(user_version)?;

        // Older database: normalize any known schema drift before running the
        // canonical migration chain. Fixtures written by prerelease code may
        // have applied parts of later schemas without bumping user_version, so
        // we add columns/indexes migrations expect when missing and recreate
        // objects that already exist to keep the migration SQL idempotent.
        conn.execute_batch("SAVEPOINT duc_legacy_normalization")
            .map_err(|e| DbError::Bootstrap(format!("legacy normalization begin failed: {e}")))?;
        if let Err(error) = normalize_legacy_schema(conn, user_version) {
            let _ = conn.execute_batch(
                "ROLLBACK TO duc_legacy_normalization;
                 RELEASE duc_legacy_normalization;",
            );
            return Err(error);
        }
        conn.execute_batch("RELEASE duc_legacy_normalization")
            .map_err(|e| DbError::Bootstrap(format!("legacy normalization commit failed: {e}")))?;

        // Walk the migration chain until we reach CURRENT_VERSION.
        // build.rs generates MIGRATIONS sorted by from_version, so chaining
        // (e.g. 3000000→3000001→3000002) works without any code changes here.
        let mut current = user_version;
        loop {
            match MIGRATIONS.iter().find(|(from, _, _)| *from == current) {
                Some((from, to, sql)) => {
                    current = apply_migration(conn, *from, *to, sql)?;
                    if current == CURRENT_VERSION {
                        break;
                    }
                }
                None => {
                    return Err(DbError::Bootstrap(format!(
                        "unsupported schema version {user_version}; expected 0 or {CURRENT_VERSION}"
                    )));
                }
            }
        }
        conn.execute_batch(CONN_PRAGMAS)
            .map_err(|e| DbError::Bootstrap(format!("pragma apply failed: {e}")))?;
    }

    validate_current_database(conn)?;
    Ok(())
}

fn bootstrap_fresh_database(conn: &Connection) -> Result<(), DbError> {
    bootstrap_fresh_database_with_schemas(conn, DUC_SCHEMA, VERSION_CONTROL_SCHEMA, SEARCH_SCHEMA)
}

fn bootstrap_fresh_database_with_schemas(
    conn: &Connection,
    duc_schema: &str,
    version_control_schema: &str,
    search_schema: &str,
) -> Result<(), DbError> {
    conn.execute_batch(CONN_PRAGMAS)
        .map_err(|error| DbError::Bootstrap(format!("pragma apply failed: {error}")))?;

    // Connection-scoped pragmas cannot run inside a transaction. Apply them
    // above, then omit their duplicate declarations from duc.sql so all DDL is
    // one rollback-safe unit.
    let transactional_duc_schema = duc_schema
        .lines()
        .filter(|line| {
            let line = line.trim_start();
            !line.starts_with("PRAGMA journal_mode")
                && !line.starts_with("PRAGMA foreign_keys")
                && !line.starts_with("PRAGMA synchronous")
        })
        .collect::<Vec<_>>()
        .join("\n");

    conn.execute_batch("SAVEPOINT duc_fresh_bootstrap")
        .map_err(|error| DbError::Bootstrap(format!("bootstrap begin failed: {error}")))?;
    let result = (|| {
        conn.execute_batch(&transactional_duc_schema)
            .map_err(|error| DbError::Bootstrap(format!("duc.sql apply failed: {error}")))?;
        conn.execute_batch(version_control_schema)
            .map_err(|error| {
                DbError::Bootstrap(format!("version_control.sql apply failed: {error}"))
            })?;
        conn.execute_batch(search_schema)
            .map_err(|error| DbError::Bootstrap(format!("search.sql apply failed: {error}")))?;

        let app_id: i64 = conn.pragma_query_value(None, "application_id", |row| row.get(0))?;
        if app_id != APP_ID {
            return Err(DbError::Bootstrap(format!(
                "unexpected application_id after bootstrap: {app_id} (expected {APP_ID})"
            )));
        }
        let schema_version: i64 =
            conn.pragma_query_value(None, "user_version", |row| row.get(0))?;
        if schema_version != CURRENT_VERSION {
            return Err(DbError::Bootstrap(format!(
                "unexpected schema version after bootstrap: {schema_version} (expected {CURRENT_VERSION})"
            )));
        }
        validate_current_database(conn)?;
        Ok(())
    })();

    match result {
        Ok(()) => conn
            .execute_batch("RELEASE duc_fresh_bootstrap")
            .map_err(|error| DbError::Bootstrap(format!("bootstrap commit failed: {error}"))),
        Err(error) => {
            let _ = conn.execute_batch(
                "ROLLBACK TO duc_fresh_bootstrap;
                 RELEASE duc_fresh_bootstrap;",
            );
            Err(error)
        }
    }
}

fn validate_current_database(conn: &Connection) -> Result<(), DbError> {
    let app_id: i64 = conn.pragma_query_value(None, "application_id", |row| row.get(0))?;
    if app_id != APP_ID {
        return Err(DbError::Bootstrap(format!(
            "unexpected application_id: {app_id} (expected {APP_ID})"
        )));
    }
    let schema_version: i64 = conn.pragma_query_value(None, "user_version", |row| row.get(0))?;
    if schema_version != CURRENT_VERSION {
        return Err(DbError::Bootstrap(format!(
            "unexpected schema version: {schema_version} (expected {CURRENT_VERSION})"
        )));
    }

    for table in [
        "version_graph",
        "schema_migrations",
        "version_chains",
        "checkpoints",
        "checkpoint_data_chunks",
        "deltas",
        "delta_changeset_chunks",
    ] {
        let exists: bool = conn.query_row(
            "SELECT EXISTS(
                SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ?1
             )",
            [table],
            |row| row.get(0),
        )?;
        if !exists {
            return Err(DbError::Bootstrap(format!(
                "current schema is missing required table {table}"
            )));
        }
    }

    let graph_rows: i64 =
        conn.query_row("SELECT COUNT(*) FROM version_graph", [], |row| row.get(0))?;
    if graph_rows > 1 {
        return Err(DbError::Bootstrap(format!(
            "version_graph may contain at most one row, found {graph_rows}"
        )));
    }

    let version_control_foreign_key_errors: i64 = conn.query_row(
        "SELECT COUNT(*) FROM pragma_foreign_key_check
         WHERE \"table\" IN (
             'version_chains', 'checkpoints', 'checkpoint_data_chunks',
             'deltas', 'delta_changeset_chunks'
         )",
        [],
        |row| row.get(0),
    )?;
    if version_control_foreign_key_errors != 0 {
        return Err(DbError::Bootstrap(format!(
            "version-control tables contain {version_control_foreign_key_errors} foreign key violations"
        )));
    }

    Ok(())
}

fn apply_migration(
    conn: &Connection,
    from_version: i64,
    to_version: i64,
    sql: &str,
) -> Result<i64, DbError> {
    if let Err(error) = conn.execute_batch(sql) {
        let _ = conn.execute_batch("ROLLBACK");
        let _ = conn.execute_batch(CONN_PRAGMAS);
        return Err(DbError::Bootstrap(format!(
            "migration {from_version}\u{2192}{to_version} failed: {error}"
        )));
    }

    let current = conn.pragma_query_value(None, "user_version", |row| row.get(0))?;
    if current != to_version {
        return Err(DbError::Bootstrap(format!(
            "migration {from_version}\u{2192}{to_version} set unexpected schema version {current}"
        )));
    }
    Ok(current)
}

fn validate_migration_path(start_version: i64) -> Result<(), DbError> {
    let mut current = start_version;
    let mut steps = 0usize;

    while current != CURRENT_VERSION {
        if current > CURRENT_VERSION || steps >= MIGRATIONS.len() {
            return Err(DbError::Bootstrap(format!(
                "unsupported schema version {start_version}; expected 0 or {CURRENT_VERSION}"
            )));
        }
        let mut matches = MIGRATIONS.iter().filter(|(from, _, _)| *from == current);
        let Some((_, to, _)) = matches.next() else {
            return Err(DbError::Bootstrap(format!(
                "unsupported schema version {start_version}; expected 0 or {CURRENT_VERSION}"
            )));
        };
        if matches.next().is_some() || *to <= current {
            return Err(DbError::Bootstrap(format!(
                "invalid migration registry at schema version {current}"
            )));
        }
        current = *to;
        steps += 1;
    }

    Ok(())
}

/// Add missing columns/objects that later migrations expect.
///
/// Some test fixtures were produced by intermediate code that created tables
/// such as `search_elements` or renamed `element_model.svg_path` to `thumbnail`
/// while still reporting an older `user_version`. Adding the missing legacy
/// columns back lets the canonical migration SQL run without modification.
fn normalize_legacy_schema(conn: &Connection, user_version: i64) -> Result<(), DbError> {
    normalize_legacy_version_graph(conn)?;

    if user_version <= 3000001 {
        normalize_external_revision_storage(conn)?;
    }

    // 3000003→3000004 migration expects `element_model.svg_path`.
    if user_version <= 3000004 {
        let has_column: bool = conn
            .query_row(
                "SELECT 1 FROM pragma_table_info('element_model') WHERE name = 'svg_path'",
                [],
                |_| Ok(true),
            )
            .unwrap_or(false);
        if !has_column {
            conn.execute(
                "ALTER TABLE element_model ADD COLUMN svg_path TEXT DEFAULT NULL",
                [],
            )
            .map_err(|e| {
                DbError::Bootstrap(format!(
                    "legacy normalization: add element_model.svg_path failed: {e}"
                ))
            })?;
        }
    }

    Ok(())
}

fn normalize_legacy_version_graph(conn: &Connection) -> Result<(), DbError> {
    let has_version_control_tables: bool = conn.query_row(
        "SELECT EXISTS(
             SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'version_graph'
         ) AND EXISTS(
             SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'version_chains'
         ) AND EXISTS(
             SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'checkpoints'
         ) AND EXISTS(
             SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'deltas'
         )",
        [],
        |row| row.get(0),
    )?;
    if !has_version_control_tables {
        return Ok(());
    }

    let invalid_groups = {
        let mut statement = conn.prepare(
            "SELECT versions.chain_id, versions.schema_version
             FROM (
                 SELECT chain_id, schema_version FROM checkpoints
                 UNION
                 SELECT chain_id, schema_version FROM deltas
             ) AS versions
             LEFT JOIN version_chains ON version_chains.id = versions.chain_id
             WHERE version_chains.id IS NULL
                OR version_chains.schema_version != versions.schema_version
             ORDER BY versions.schema_version, versions.chain_id",
        )?;
        let groups = statement
            .query_map([], |row| {
                Ok((row.get::<_, String>(0)?, row.get::<_, i32>(1)?))
            })?
            .collect::<rusqlite::Result<Vec<_>>>()?;
        groups
    };
    if invalid_groups.is_empty() {
        return Ok(());
    }

    let current_schema_version: i32 = conn
        .query_row(
            "SELECT current_schema_version FROM version_graph WHERE id = 1",
            [],
            |row| row.get(0),
        )
        .unwrap_or(1);

    for (group_index, (legacy_chain_id, schema_version)) in invalid_groups.into_iter().enumerate() {
        let (start_version, end_version): (Option<i64>, Option<i64>) = conn.query_row(
            "SELECT MIN(version_number), MAX(version_number) FROM (
                 SELECT version_number FROM checkpoints
                 WHERE chain_id = ?1 AND schema_version = ?2
                 UNION ALL
                 SELECT version_number FROM deltas
                 WHERE chain_id = ?1 AND schema_version = ?2
             )",
            rusqlite::params![legacy_chain_id, schema_version],
            |row| Ok((row.get(0)?, row.get(1)?)),
        )?;
        let (Some(start_version), Some(last_version)) = (start_version, end_version) else {
            continue;
        };
        let root_checkpoint_id: Option<String> = conn
            .query_row(
                "SELECT id FROM checkpoints
                 WHERE chain_id = ?1 AND schema_version = ?2
                 ORDER BY version_number
                 LIMIT 1",
                rusqlite::params![legacy_chain_id, schema_version],
                |row| row.get(0),
            )
            .optional()?;

        let legacy_id_available: bool = !legacy_chain_id.is_empty()
            && !conn.query_row(
                "SELECT EXISTS(SELECT 1 FROM version_chains WHERE id = ?1)",
                [&legacy_chain_id],
                |row| row.get(0),
            )?;
        let mut repaired_chain_id = if legacy_id_available {
            legacy_chain_id.clone()
        } else {
            format!("legacy-chain-{schema_version}")
        };
        let mut suffix = group_index;
        while conn.query_row(
            "SELECT EXISTS(SELECT 1 FROM version_chains WHERE id = ?1)",
            [&repaired_chain_id],
            |row| row.get::<_, bool>(0),
        )? {
            suffix += 1;
            repaired_chain_id = format!("legacy-chain-{schema_version}-{suffix}");
        }

        let repaired_end_version =
            (schema_version != current_schema_version).then_some(last_version);
        conn.execute(
            "INSERT INTO version_chains
                (id, schema_version, start_version, end_version, root_checkpoint_id)
             VALUES (?1, ?2, ?3, ?4, ?5)",
            rusqlite::params![
                repaired_chain_id,
                schema_version,
                start_version,
                repaired_end_version,
                root_checkpoint_id,
            ],
        )?;
        conn.execute(
            "UPDATE checkpoints SET chain_id = ?1
             WHERE chain_id = ?2 AND schema_version = ?3",
            rusqlite::params![repaired_chain_id, legacy_chain_id, schema_version],
        )?;
        conn.execute(
            "UPDATE deltas SET chain_id = ?1
             WHERE chain_id = ?2 AND schema_version = ?3",
            rusqlite::params![repaired_chain_id, legacy_chain_id, schema_version],
        )?;
        conn.execute(
            "DELETE FROM version_chains
             WHERE id = ?1
               AND NOT EXISTS (SELECT 1 FROM checkpoints WHERE chain_id = ?1)
               AND NOT EXISTS (SELECT 1 FROM deltas WHERE chain_id = ?1)",
            [&legacy_chain_id],
        )?;
    }

    conn.execute(
        "UPDATE version_graph
         SET chain_count = MAX(1, (SELECT COUNT(*) FROM version_chains))
         WHERE id = 1",
        [],
    )?;

    Ok(())
}

fn normalize_external_revision_storage(conn: &Connection) -> Result<(), DbError> {
    let table_exists = |table: &str| -> rusqlite::Result<bool> {
        conn.query_row(
            "SELECT EXISTS(
                SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ?1
             )",
            [table],
            |row| row.get(0),
        )
    };
    let column_exists = |table: &str, column: &str| -> rusqlite::Result<bool> {
        conn.query_row(
            "SELECT EXISTS(
                SELECT 1 FROM pragma_table_info(?1) WHERE name = ?2
             )",
            [table, column],
            |row| row.get(0),
        )
    };

    if !table_exists("external_file_revisions")? {
        return Ok(());
    }

    if !column_exists("external_file_revisions", "data")? {
        conn.execute(
            "ALTER TABLE external_file_revisions ADD COLUMN data BLOB",
            [],
        )
        .map_err(|error| {
            DbError::Bootstrap(format!(
                "legacy normalization: add external_file_revisions.data failed: {error}"
            ))
        })?;
    }

    for source_table in [
        "_external_file_revision_data_v3000001",
        "external_file_revision_data",
    ] {
        if table_exists(source_table)? {
            let sql = format!(
                "UPDATE external_file_revisions
                 SET data = (
                     SELECT source.data FROM {source_table} AS source
                     WHERE source.revision_id = external_file_revisions.id
                 )
                 WHERE data IS NULL AND EXISTS (
                     SELECT 1 FROM {source_table} AS source
                     WHERE source.revision_id = external_file_revisions.id
                 )"
            );
            conn.execute(&sql, []).map_err(|error| {
                DbError::Bootstrap(format!(
                    "legacy normalization: restore revision data from {source_table} failed: {error}"
                ))
            })?;
        }
    }

    if table_exists("external_file_revision_chunks")? {
        let revision_ids = {
            let mut statement = conn
                .prepare(
                    "SELECT id FROM external_file_revisions
                     WHERE data IS NULL
                     ORDER BY id",
                )
                .map_err(|error| {
                    DbError::Bootstrap(format!(
                        "legacy normalization: list chunked revisions failed: {error}"
                    ))
                })?;
            let rows = statement
                .query_map([], |row| row.get::<_, String>(0))
                .map_err(|error| {
                    DbError::Bootstrap(format!(
                        "legacy normalization: query chunked revisions failed: {error}"
                    ))
                })?;
            rows.collect::<rusqlite::Result<Vec<_>>>()
                .map_err(|error| {
                    DbError::Bootstrap(format!(
                        "legacy normalization: read chunked revisions failed: {error}"
                    ))
                })?
        };

        for revision_id in revision_ids {
            let data = crate::external_file_chunks::read_revision_chunks(conn, &revision_id)
                .map_err(|error| {
                    DbError::Bootstrap(format!(
                        "legacy normalization: read chunks for revision {revision_id} failed: {error}"
                    ))
                })?;
            if !data.is_empty() {
                conn.execute(
                    "UPDATE external_file_revisions SET data = ?2 WHERE id = ?1",
                    rusqlite::params![revision_id, data],
                )
                .map_err(|error| {
                    DbError::Bootstrap(format!(
                        "legacy normalization: restore chunks for revision failed: {error}"
                    ))
                })?;
            }
        }
    }

    conn.execute(
        "UPDATE external_file_revisions
         SET data = X''
         WHERE data IS NULL AND size_bytes = 0",
        [],
    )?;
    let missing_data: i64 = conn.query_row(
        "SELECT count(*) FROM external_file_revisions
         WHERE data IS NULL",
        [],
        |row| row.get(0),
    )?;
    if missing_data > 0 {
        return Err(DbError::Bootstrap(format!(
            "legacy normalization: {missing_data} external file revisions have metadata but no recoverable data"
        )));
    }

    for table in [
        "external_file_revision_chunks",
        "external_file_revision_data",
        "_external_file_revision_data_v3000001",
    ] {
        if table_exists(table)? {
            conn.execute_batch(&format!("DROP TABLE {table}"))
                .map_err(|error| {
                    DbError::Bootstrap(format!(
                        "legacy normalization: drop superseded {table} failed: {error}"
                    ))
                })?;
        }
    }

    Ok(())
}

#[cfg(test)]
#[path = "bootstrap_tests.rs"]
mod tests;
