# Automatically generated by SST
# pylint: disable=all
# ruff: noqa
from typing import Any

class Resource:
    class App:
        name: str
        stage: str
    class MyWeb:
        type: str
        url: str

