# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Duconfig

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# User's personal application settings, applied across all projects
class Duconfig(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Duconfig()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDuconfig(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def DuconfigBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x46\x49\x47", size_prefixed=size_prefixed)

    # Duconfig
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Duconfig
    def Theme(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 10

    # Duconfig
    def AntiAliasing(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 11

    # Duconfig
    def ShowHyperlinkPopup(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 11

    # Duconfig
    def ZoomStep(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Duconfig
    def VSync(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Duconfig
    def ScaleRatioLocked(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Duconfig
    def DisplayAllPointDistances(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Duconfig
    def DisplayDistanceOnDrawing(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Duconfig
    def DisplayAllPointCoordinates(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Duconfig
    def DisplayAllPointInfoSelected(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Duconfig
    def DisplayRootAxis(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Duconfig
    def DebugRendering(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Duconfig
    def ManualSaveMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Duconfig
    def DefaultVersionGraphPruningLevel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 20

def DuconfigStart(builder):
    builder.StartObject(14)

def Start(builder):
    DuconfigStart(builder)

def DuconfigAddTheme(builder, theme):
    builder.PrependUint8Slot(0, theme, 10)

def AddTheme(builder, theme):
    DuconfigAddTheme(builder, theme)

def DuconfigAddAntiAliasing(builder, antiAliasing):
    builder.PrependUint8Slot(1, antiAliasing, 11)

def AddAntiAliasing(builder, antiAliasing):
    DuconfigAddAntiAliasing(builder, antiAliasing)

def DuconfigAddShowHyperlinkPopup(builder, showHyperlinkPopup):
    builder.PrependUint8Slot(2, showHyperlinkPopup, 11)

def AddShowHyperlinkPopup(builder, showHyperlinkPopup):
    DuconfigAddShowHyperlinkPopup(builder, showHyperlinkPopup)

def DuconfigAddZoomStep(builder, zoomStep):
    builder.PrependFloat32Slot(3, zoomStep, 0.0)

def AddZoomStep(builder, zoomStep):
    DuconfigAddZoomStep(builder, zoomStep)

def DuconfigAddVSync(builder, vSync):
    builder.PrependBoolSlot(4, vSync, 0)

def AddVSync(builder, vSync):
    DuconfigAddVSync(builder, vSync)

def DuconfigAddScaleRatioLocked(builder, scaleRatioLocked):
    builder.PrependBoolSlot(5, scaleRatioLocked, 0)

def AddScaleRatioLocked(builder, scaleRatioLocked):
    DuconfigAddScaleRatioLocked(builder, scaleRatioLocked)

def DuconfigAddDisplayAllPointDistances(builder, displayAllPointDistances):
    builder.PrependBoolSlot(6, displayAllPointDistances, 0)

def AddDisplayAllPointDistances(builder, displayAllPointDistances):
    DuconfigAddDisplayAllPointDistances(builder, displayAllPointDistances)

def DuconfigAddDisplayDistanceOnDrawing(builder, displayDistanceOnDrawing):
    builder.PrependBoolSlot(7, displayDistanceOnDrawing, 0)

def AddDisplayDistanceOnDrawing(builder, displayDistanceOnDrawing):
    DuconfigAddDisplayDistanceOnDrawing(builder, displayDistanceOnDrawing)

def DuconfigAddDisplayAllPointCoordinates(builder, displayAllPointCoordinates):
    builder.PrependBoolSlot(8, displayAllPointCoordinates, 0)

def AddDisplayAllPointCoordinates(builder, displayAllPointCoordinates):
    DuconfigAddDisplayAllPointCoordinates(builder, displayAllPointCoordinates)

def DuconfigAddDisplayAllPointInfoSelected(builder, displayAllPointInfoSelected):
    builder.PrependBoolSlot(9, displayAllPointInfoSelected, 0)

def AddDisplayAllPointInfoSelected(builder, displayAllPointInfoSelected):
    DuconfigAddDisplayAllPointInfoSelected(builder, displayAllPointInfoSelected)

def DuconfigAddDisplayRootAxis(builder, displayRootAxis):
    builder.PrependBoolSlot(10, displayRootAxis, 0)

def AddDisplayRootAxis(builder, displayRootAxis):
    DuconfigAddDisplayRootAxis(builder, displayRootAxis)

def DuconfigAddDebugRendering(builder, debugRendering):
    builder.PrependBoolSlot(11, debugRendering, 0)

def AddDebugRendering(builder, debugRendering):
    DuconfigAddDebugRendering(builder, debugRendering)

def DuconfigAddManualSaveMode(builder, manualSaveMode):
    builder.PrependBoolSlot(12, manualSaveMode, 0)

def AddManualSaveMode(builder, manualSaveMode):
    DuconfigAddManualSaveMode(builder, manualSaveMode)

def DuconfigAddDefaultVersionGraphPruningLevel(builder, defaultVersionGraphPruningLevel):
    builder.PrependUint8Slot(13, defaultVersionGraphPruningLevel, 20)

def AddDefaultVersionGraphPruningLevel(builder, defaultVersionGraphPruningLevel):
    DuconfigAddDefaultVersionGraphPruningLevel(builder, defaultVersionGraphPruningLevel)

def DuconfigEnd(builder):
    return builder.EndObject()

def End(builder):
    return DuconfigEnd(builder)
