"""Search helpers for DUC SQLite databases."""

from .search_build123d import (
    Build123dText,
    Build123dTextItem,
    extract_build123d_path_text,
    extract_build123d_shape_text,
    extract_build123d_text,
    extract_model_build123d_text,
)
from .search_charter_issues import (
    DucCharterIssueSearchResponse,
    DucCharterIssueSearchResult,
    DucCharterSearchResult,
    DucIssueSearchResult,
    search_duc_charter,
    search_duc_charter_and_issues,
    search_duc_issues,
)
from .search_elements import (
    DucElementSearchResult,
    DucFileSearchResult,
    DucSearchResponse,
    DucSearchResult,
    ExternalFileSearchTarget,
    search_duc_elements,
)
from .search_ezdxf import (
    DWGDXF_WASM_PATH_ENV,
    DWGDXF_WASM_URL,
    DwgConversionNotAvailable,
    DxfText,
    DxfTextItem,
    convert_dwg_to_dxf,
    extract_dxf_text,
    extract_model_dxf_text,
)
from .search_ifc import (
    IfcText,
    IfcTextItem,
    extract_ifc_file_text,
    extract_ifc_path_text,
    extract_ifc_text,
    extract_model_ifc_text,
)
from .search_models import (
    ModelElementInfo,
    ModelEngine,
    detect_model_engine,
    search_duc_models,
)

__all__ = [
    "DWGDXF_WASM_PATH_ENV",
    "DWGDXF_WASM_URL",
    "Build123dText",
    "Build123dTextItem",
    "DucCharterIssueSearchResponse",
    "DucCharterIssueSearchResult",
    "DucCharterSearchResult",
    "DucElementSearchResult",
    "DucFileSearchResult",
    "DucIssueSearchResult",
    "DucSearchResponse",
    "DucSearchResult",
    "DwgConversionNotAvailable",
    "DxfText",
    "DxfTextItem",
    "ExternalFileSearchTarget",
    "IfcText",
    "IfcTextItem",
    "ModelElementInfo",
    "ModelEngine",
    "convert_dwg_to_dxf",
    "detect_model_engine",
    "extract_build123d_path_text",
    "extract_build123d_shape_text",
    "extract_build123d_text",
    "extract_dxf_text",
    "extract_ifc_file_text",
    "extract_ifc_path_text",
    "extract_ifc_text",
    "extract_model_build123d_text",
    "extract_model_dxf_text",
    "extract_model_ifc_text",
    "search_duc_charter",
    "search_duc_charter_and_issues",
    "search_duc_elements",
    "search_duc_issues",
    "search_duc_models",
]
