// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class DucBlockInstanceElementOverride {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DucBlockInstanceElementOverride {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDucBlockInstanceElementOverride(bb:flatbuffers.ByteBuffer, obj?:DucBlockInstanceElementOverride):DucBlockInstanceElementOverride {
  return (obj || new DucBlockInstanceElementOverride()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDucBlockInstanceElementOverride(bb:flatbuffers.ByteBuffer, obj?:DucBlockInstanceElementOverride):DucBlockInstanceElementOverride {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DucBlockInstanceElementOverride()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

elementId():string|null
elementId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
elementId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

overrides():string|null
overrides(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
overrides(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startDucBlockInstanceElementOverride(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addElementId(builder:flatbuffers.Builder, elementIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, elementIdOffset, 0);
}

static addOverrides(builder:flatbuffers.Builder, overridesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, overridesOffset, 0);
}

static endDucBlockInstanceElementOverride(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createDucBlockInstanceElementOverride(builder:flatbuffers.Builder, elementIdOffset:flatbuffers.Offset, overridesOffset:flatbuffers.Offset):flatbuffers.Offset {
  DucBlockInstanceElementOverride.startDucBlockInstanceElementOverride(builder);
  DucBlockInstanceElementOverride.addElementId(builder, elementIdOffset);
  DucBlockInstanceElementOverride.addOverrides(builder, overridesOffset);
  return DucBlockInstanceElementOverride.endDucBlockInstanceElementOverride(builder);
}
}
