[package]
name = "ducflair-duc"
version = "1.1.0"
edition = "2021"
description = "The duc 2D CAD file format Rust implementation"
license = "MIT"
authors = ["Ducflair support@ducflair.com"]
repository = "https://github.com/ducflair/duc/tree/main/packages/duc-rs"
readme = "README.md"

[dependencies]

[dev-dependencies]
