[package]
name = "duc"
version = "0.0.0-development"
edition = "2021"
description = "The duc 2D CAD file format Rust implementation."
license = "MIT"
authors = ["Ducflair support@ducflair.com"]
repository = "https://github.com/ducflair/duc/tree/main/packages/duc-rs"
readme = "README.md"


[dependencies]
flatbuffers = "24.3.25"
base64 = "0.21.5"
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }

[features]
default = []
serde_support = ["serde", "serde_json"]