# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Duc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DatumReference(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DatumReference()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDatumReference(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def DatumReferenceBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x55\x43\x5F", size_prefixed=size_prefixed)

    # DatumReference
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DatumReference
    def Letters(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DatumReference
    def Modifier(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return None

def DatumReferenceStart(builder):
    builder.StartObject(2)

def Start(builder):
    DatumReferenceStart(builder)

def DatumReferenceAddLetters(builder, letters):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(letters), 0)

def AddLetters(builder, letters):
    DatumReferenceAddLetters(builder, letters)

def DatumReferenceAddModifier(builder, modifier):
    builder.PrependUint8Slot(1, modifier, None)

def AddModifier(builder, modifier):
    DatumReferenceAddModifier(builder, modifier)

def DatumReferenceEnd(builder):
    return builder.EndObject()

def End(builder):
    return DatumReferenceEnd(builder)
