# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Duc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DocumentGridConfig(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DocumentGridConfig()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDocumentGridConfig(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def DocumentGridConfigBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x55\x43\x5F", size_prefixed=size_prefixed)

    # DocumentGridConfig
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DocumentGridConfig
    def Columns(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DocumentGridConfig
    def GapX(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # DocumentGridConfig
    def GapY(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # DocumentGridConfig
    def AlignItems(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return None

    # DocumentGridConfig
    def FirstPageAlone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def DocumentGridConfigStart(builder):
    builder.StartObject(5)

def Start(builder):
    DocumentGridConfigStart(builder)

def DocumentGridConfigAddColumns(builder, columns):
    builder.PrependInt32Slot(0, columns, 0)

def AddColumns(builder, columns):
    DocumentGridConfigAddColumns(builder, columns)

def DocumentGridConfigAddGapX(builder, gapX):
    builder.PrependFloat64Slot(1, gapX, 0.0)

def AddGapX(builder, gapX):
    DocumentGridConfigAddGapX(builder, gapX)

def DocumentGridConfigAddGapY(builder, gapY):
    builder.PrependFloat64Slot(2, gapY, 0.0)

def AddGapY(builder, gapY):
    DocumentGridConfigAddGapY(builder, gapY)

def DocumentGridConfigAddAlignItems(builder, alignItems):
    builder.PrependUint8Slot(3, alignItems, None)

def AddAlignItems(builder, alignItems):
    DocumentGridConfigAddAlignItems(builder, alignItems)

def DocumentGridConfigAddFirstPageAlone(builder, firstPageAlone):
    builder.PrependBoolSlot(4, firstPageAlone, 0)

def AddFirstPageAlone(builder, firstPageAlone):
    DocumentGridConfigAddFirstPageAlone(builder, firstPageAlone)

def DocumentGridConfigEnd(builder):
    return builder.EndObject()

def End(builder):
    return DocumentGridConfigEnd(builder)
