# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Duc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DucArrowElement(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DucArrowElement()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDucArrowElement(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def DucArrowElementBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x55\x43\x5F", size_prefixed=size_prefixed)

    # DucArrowElement
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DucArrowElement
    def LinearBase(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Duc._DucLinearElementBase import _DucLinearElementBase
            obj = _DucLinearElementBase()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DucArrowElement
    def Elbowed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def DucArrowElementStart(builder):
    builder.StartObject(2)

def Start(builder):
    DucArrowElementStart(builder)

def DucArrowElementAddLinearBase(builder, linearBase):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(linearBase), 0)

def AddLinearBase(builder, linearBase):
    DucArrowElementAddLinearBase(builder, linearBase)

def DucArrowElementAddElbowed(builder, elbowed):
    builder.PrependBoolSlot(1, elbowed, 0)

def AddElbowed(builder, elbowed):
    DucArrowElementAddElbowed(builder, elbowed)

def DucArrowElementEnd(builder):
    return builder.EndObject()

def End(builder):
    return DucArrowElementEnd(builder)
