# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Duc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DucBlockInstanceElement(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DucBlockInstanceElement()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDucBlockInstanceElement(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def DucBlockInstanceElementBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x55\x43\x5F", size_prefixed=size_prefixed)

    # DucBlockInstanceElement
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def DucBlockInstanceElementStart(builder):
    builder.StartObject(5)

def Start(builder):
    DucBlockInstanceElementStart(builder)

def DucBlockInstanceElementEnd(builder):
    return builder.EndObject()

def End(builder):
    return DucBlockInstanceElementEnd(builder)
