# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Duc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DucBlockCollection(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DucBlockCollection()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDucBlockCollection(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def DucBlockCollectionBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x55\x43\x5F", size_prefixed=size_prefixed)

    # DucBlockCollection
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DucBlockCollection
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DucBlockCollection
    def Label(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DucBlockCollection
    def Children(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Duc.DucBlockCollectionEntry import DucBlockCollectionEntry
            obj = DucBlockCollectionEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DucBlockCollection
    def ChildrenLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DucBlockCollection
    def ChildrenIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # DucBlockCollection
    def Metadata(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Duc.DucBlockMetadata import DucBlockMetadata
            obj = DucBlockMetadata()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DucBlockCollection
    def Thumbnail(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # DucBlockCollection
    def ThumbnailAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # DucBlockCollection
    def ThumbnailLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DucBlockCollection
    def ThumbnailIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

def DucBlockCollectionStart(builder):
    builder.StartObject(5)

def Start(builder):
    DucBlockCollectionStart(builder)

def DucBlockCollectionAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    DucBlockCollectionAddId(builder, id)

def DucBlockCollectionAddLabel(builder, label):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(label), 0)

def AddLabel(builder, label):
    DucBlockCollectionAddLabel(builder, label)

def DucBlockCollectionAddChildren(builder, children):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(children), 0)

def AddChildren(builder, children):
    DucBlockCollectionAddChildren(builder, children)

def DucBlockCollectionStartChildrenVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartChildrenVector(builder, numElems):
    return DucBlockCollectionStartChildrenVector(builder, numElems)

def DucBlockCollectionAddMetadata(builder, metadata):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(metadata), 0)

def AddMetadata(builder, metadata):
    DucBlockCollectionAddMetadata(builder, metadata)

def DucBlockCollectionAddThumbnail(builder, thumbnail):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(thumbnail), 0)

def AddThumbnail(builder, thumbnail):
    DucBlockCollectionAddThumbnail(builder, thumbnail)

def DucBlockCollectionStartThumbnailVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartThumbnailVector(builder, numElems):
    return DucBlockCollectionStartThumbnailVector(builder, numElems)

def DucBlockCollectionEnd(builder):
    return builder.EndObject()

def End(builder):
    return DucBlockCollectionEnd(builder)
