# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Duc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DucBlockAttributeDetails(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DucBlockAttributeDetails()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDucBlockAttributeDetails(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def DucBlockAttributeDetailsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x55\x43\x5F", size_prefixed=size_prefixed)

    # DucBlockAttributeDetails
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DucBlockAttributeDetails
    def Tag(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DucBlockAttributeDetails
    def DefaultValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DucBlockAttributeDetails
    def Prompt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DucBlockAttributeDetails
    def Position(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Duc.SimplePoint import SimplePoint
            obj = SimplePoint()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def DucBlockAttributeDetailsStart(builder):
    builder.StartObject(4)

def Start(builder):
    DucBlockAttributeDetailsStart(builder)

def DucBlockAttributeDetailsAddTag(builder, tag):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(tag), 0)

def AddTag(builder, tag):
    DucBlockAttributeDetailsAddTag(builder, tag)

def DucBlockAttributeDetailsAddDefaultValue(builder, defaultValue):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(defaultValue), 0)

def AddDefaultValue(builder, defaultValue):
    DucBlockAttributeDetailsAddDefaultValue(builder, defaultValue)

def DucBlockAttributeDetailsAddPrompt(builder, prompt):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(prompt), 0)

def AddPrompt(builder, prompt):
    DucBlockAttributeDetailsAddPrompt(builder, prompt)

def DucBlockAttributeDetailsAddPosition(builder, position):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(position), 0)

def AddPosition(builder, position):
    DucBlockAttributeDetailsAddPosition(builder, position)

def DucBlockAttributeDetailsEnd(builder):
    return builder.EndObject()

def End(builder):
    return DucBlockAttributeDetailsEnd(builder)
