# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Duc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DucDocStyle(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DucDocStyle()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDucDocStyle(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def DucDocStyleBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x55\x43\x5F", size_prefixed=size_prefixed)

    # DucDocStyle
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DucDocStyle
    def TextStyle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Duc.DucTextStyle import DucTextStyle
            obj = DucTextStyle()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DucDocStyle
    def Paragraph(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Duc.ParagraphFormatting import ParagraphFormatting
            obj = ParagraphFormatting()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DucDocStyle
    def StackFormat(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Duc.StackFormat import StackFormat
            obj = StackFormat()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def DucDocStyleStart(builder):
    builder.StartObject(3)

def Start(builder):
    DucDocStyleStart(builder)

def DucDocStyleAddTextStyle(builder, textStyle):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(textStyle), 0)

def AddTextStyle(builder, textStyle):
    DucDocStyleAddTextStyle(builder, textStyle)

def DucDocStyleAddParagraph(builder, paragraph):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(paragraph), 0)

def AddParagraph(builder, paragraph):
    DucDocStyleAddParagraph(builder, paragraph)

def DucDocStyleAddStackFormat(builder, stackFormat):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(stackFormat), 0)

def AddStackFormat(builder, stackFormat):
    DucDocStyleAddStackFormat(builder, stackFormat)

def DucDocStyleEnd(builder):
    return builder.EndObject()

def End(builder):
    return DucDocStyleEnd(builder)
