# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Duc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DucHead(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DucHead()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDucHead(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def DucHeadBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x55\x43\x5F", size_prefixed=size_prefixed)

    # DucHead
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DucHead
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return None

    # DucHead
    def BlockId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DucHead
    def Size(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def DucHeadStart(builder):
    builder.StartObject(3)

def Start(builder):
    DucHeadStart(builder)

def DucHeadAddType(builder, type):
    builder.PrependUint8Slot(0, type, None)

def AddType(builder, type):
    DucHeadAddType(builder, type)

def DucHeadAddBlockId(builder, blockId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(blockId), 0)

def AddBlockId(builder, blockId):
    DucHeadAddBlockId(builder, blockId)

def DucHeadAddSize(builder, size):
    builder.PrependFloat64Slot(2, size, 0.0)

def AddSize(builder, size):
    DucHeadAddSize(builder, size)

def DucHeadEnd(builder):
    return builder.EndObject()

def End(builder):
    return DucHeadEnd(builder)
