# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Duc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DucPoint(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DucPoint()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDucPoint(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def DucPointBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x55\x43\x5F", size_prefixed=size_prefixed)

    # DucPoint
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DucPoint
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # DucPoint
    def Y(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # DucPoint
    def Mirroring(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return None

def DucPointStart(builder):
    builder.StartObject(3)

def Start(builder):
    DucPointStart(builder)

def DucPointAddX(builder, x):
    builder.PrependFloat64Slot(0, x, 0.0)

def AddX(builder, x):
    DucPointAddX(builder, x)

def DucPointAddY(builder, y):
    builder.PrependFloat64Slot(1, y, 0.0)

def AddY(builder, y):
    DucPointAddY(builder, y)

def DucPointAddMirroring(builder, mirroring):
    builder.PrependUint8Slot(2, mirroring, None)

def AddMirroring(builder, mirroring):
    DucPointAddMirroring(builder, mirroring)

def DucPointEnd(builder):
    return builder.EndObject()

def End(builder):
    return DucPointEnd(builder)
