# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Duc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DucTableCellSpan(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DucTableCellSpan()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDucTableCellSpan(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def DucTableCellSpanBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x55\x43\x5F", size_prefixed=size_prefixed)

    # DucTableCellSpan
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DucTableCellSpan
    def Columns(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DucTableCellSpan
    def Rows(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def DucTableCellSpanStart(builder):
    builder.StartObject(2)

def Start(builder):
    DucTableCellSpanStart(builder)

def DucTableCellSpanAddColumns(builder, columns):
    builder.PrependInt32Slot(0, columns, 0)

def AddColumns(builder, columns):
    DucTableCellSpanAddColumns(builder, columns)

def DucTableCellSpanAddRows(builder, rows):
    builder.PrependInt32Slot(1, rows, 0)

def AddRows(builder, rows):
    DucTableCellSpanAddRows(builder, rows)

def DucTableCellSpanEnd(builder):
    return builder.EndObject()

def End(builder):
    return DucTableCellSpanEnd(builder)
