# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Duc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DynamicSnapSettings(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DynamicSnapSettings()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDynamicSnapSettings(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def DynamicSnapSettingsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x55\x43\x5F", size_prefixed=size_prefixed)

    # DynamicSnapSettings
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DynamicSnapSettings
    def EnabledDuringDrag(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # DynamicSnapSettings
    def EnabledDuringRotation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # DynamicSnapSettings
    def EnabledDuringScale(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def DynamicSnapSettingsStart(builder):
    builder.StartObject(3)

def Start(builder):
    DynamicSnapSettingsStart(builder)

def DynamicSnapSettingsAddEnabledDuringDrag(builder, enabledDuringDrag):
    builder.PrependBoolSlot(0, enabledDuringDrag, 0)

def AddEnabledDuringDrag(builder, enabledDuringDrag):
    DynamicSnapSettingsAddEnabledDuringDrag(builder, enabledDuringDrag)

def DynamicSnapSettingsAddEnabledDuringRotation(builder, enabledDuringRotation):
    builder.PrependBoolSlot(1, enabledDuringRotation, 0)

def AddEnabledDuringRotation(builder, enabledDuringRotation):
    DynamicSnapSettingsAddEnabledDuringRotation(builder, enabledDuringRotation)

def DynamicSnapSettingsAddEnabledDuringScale(builder, enabledDuringScale):
    builder.PrependBoolSlot(2, enabledDuringScale, 0)

def AddEnabledDuringScale(builder, enabledDuringScale):
    DynamicSnapSettingsAddEnabledDuringScale(builder, enabledDuringScale)

def DynamicSnapSettingsEnd(builder):
    return builder.EndObject()

def End(builder):
    return DynamicSnapSettingsEnd(builder)
