# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Duc

class Element(object):
    NONE = 0
    DucRectangleElement = 1
    DucPolygonElement = 2
    DucEllipseElement = 3
    DucEmbeddableElement = 4
    DucPdfElement = 5
    DucMermaidElement = 6
    DucTableElement = 7
    DucImageElement = 8
    DucTextElement = 9
    DucLinearElement = 10
    DucArrowElement = 11
    DucFreeDrawElement = 12
    DucBlockInstanceElement = 13
    DucFrameElement = 14
    DucPlotElement = 15
    DucViewportElement = 16
    DucXRayElement = 17
    DucLeaderElement = 18
    DucDimensionElement = 19
    DucFeatureControlFrameElement = 20
    DucDocElement = 21
    DucParametricElement = 22
    DucModelElement = 23
