# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Duc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ExportedDataState(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ExportedDataState()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsExportedDataState(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ExportedDataStateBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x55\x43\x5F", size_prefixed=size_prefixed)

    # ExportedDataState
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ExportedDataState
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ExportedDataState
    def Source(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ExportedDataState
    def Version(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ExportedDataState
    def Thumbnail(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # ExportedDataState
    def ThumbnailAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # ExportedDataState
    def ThumbnailLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ExportedDataState
    def ThumbnailIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # ExportedDataState
    def Dictionary(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Duc.DictionaryEntry import DictionaryEntry
            obj = DictionaryEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ExportedDataState
    def DictionaryLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ExportedDataState
    def DictionaryIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # ExportedDataState
    def Elements(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Duc.ElementWrapper import ElementWrapper
            obj = ElementWrapper()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ExportedDataState
    def ElementsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ExportedDataState
    def ElementsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # ExportedDataState
    def Blocks(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Duc.DucBlock import DucBlock
            obj = DucBlock()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ExportedDataState
    def BlocksLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ExportedDataState
    def BlocksIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # ExportedDataState
    def Groups(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Duc.DucGroup import DucGroup
            obj = DucGroup()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ExportedDataState
    def GroupsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ExportedDataState
    def GroupsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

    # ExportedDataState
    def Regions(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Duc.DucRegion import DucRegion
            obj = DucRegion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ExportedDataState
    def RegionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ExportedDataState
    def RegionsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        return o == 0

    # ExportedDataState
    def Layers(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Duc.DucLayer import DucLayer
            obj = DucLayer()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ExportedDataState
    def LayersLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ExportedDataState
    def LayersIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        return o == 0

    # ExportedDataState
    def Standards(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Duc.Standard import Standard
            obj = Standard()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ExportedDataState
    def StandardsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ExportedDataState
    def StandardsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        return o == 0

    # ExportedDataState
    def DucLocalState(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Duc.DucLocalState import DucLocalState
            obj = DucLocalState()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ExportedDataState
    def DucGlobalState(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Duc.DucGlobalState import DucGlobalState
            obj = DucGlobalState()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ExportedDataState
    def ExternalFiles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Duc.DucExternalFileEntry import DucExternalFileEntry
            obj = DucExternalFileEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ExportedDataState
    def ExternalFilesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ExportedDataState
    def ExternalFilesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        return o == 0

    # ExportedDataState
    def VersionGraph(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Duc.VersionGraph import VersionGraph
            obj = VersionGraph()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def ExportedDataStateStart(builder):
    builder.StartObject(16)

def Start(builder):
    ExportedDataStateStart(builder)

def ExportedDataStateAddType(builder, type):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(type), 0)

def AddType(builder, type):
    ExportedDataStateAddType(builder, type)

def ExportedDataStateAddSource(builder, source):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(source), 0)

def AddSource(builder, source):
    ExportedDataStateAddSource(builder, source)

def ExportedDataStateAddVersion(builder, version):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(version), 0)

def AddVersion(builder, version):
    ExportedDataStateAddVersion(builder, version)

def ExportedDataStateAddThumbnail(builder, thumbnail):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(thumbnail), 0)

def AddThumbnail(builder, thumbnail):
    ExportedDataStateAddThumbnail(builder, thumbnail)

def ExportedDataStateStartThumbnailVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartThumbnailVector(builder, numElems):
    return ExportedDataStateStartThumbnailVector(builder, numElems)

def ExportedDataStateAddDictionary(builder, dictionary):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(dictionary), 0)

def AddDictionary(builder, dictionary):
    ExportedDataStateAddDictionary(builder, dictionary)

def ExportedDataStateStartDictionaryVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDictionaryVector(builder, numElems):
    return ExportedDataStateStartDictionaryVector(builder, numElems)

def ExportedDataStateAddElements(builder, elements):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(elements), 0)

def AddElements(builder, elements):
    ExportedDataStateAddElements(builder, elements)

def ExportedDataStateStartElementsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartElementsVector(builder, numElems):
    return ExportedDataStateStartElementsVector(builder, numElems)

def ExportedDataStateAddBlocks(builder, blocks):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(blocks), 0)

def AddBlocks(builder, blocks):
    ExportedDataStateAddBlocks(builder, blocks)

def ExportedDataStateStartBlocksVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartBlocksVector(builder, numElems):
    return ExportedDataStateStartBlocksVector(builder, numElems)

def ExportedDataStateAddGroups(builder, groups):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(groups), 0)

def AddGroups(builder, groups):
    ExportedDataStateAddGroups(builder, groups)

def ExportedDataStateStartGroupsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartGroupsVector(builder, numElems):
    return ExportedDataStateStartGroupsVector(builder, numElems)

def ExportedDataStateAddRegions(builder, regions):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(regions), 0)

def AddRegions(builder, regions):
    ExportedDataStateAddRegions(builder, regions)

def ExportedDataStateStartRegionsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartRegionsVector(builder, numElems):
    return ExportedDataStateStartRegionsVector(builder, numElems)

def ExportedDataStateAddLayers(builder, layers):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(layers), 0)

def AddLayers(builder, layers):
    ExportedDataStateAddLayers(builder, layers)

def ExportedDataStateStartLayersVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartLayersVector(builder, numElems):
    return ExportedDataStateStartLayersVector(builder, numElems)

def ExportedDataStateAddStandards(builder, standards):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(standards), 0)

def AddStandards(builder, standards):
    ExportedDataStateAddStandards(builder, standards)

def ExportedDataStateStartStandardsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartStandardsVector(builder, numElems):
    return ExportedDataStateStartStandardsVector(builder, numElems)

def ExportedDataStateAddDucLocalState(builder, ducLocalState):
    builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(ducLocalState), 0)

def AddDucLocalState(builder, ducLocalState):
    ExportedDataStateAddDucLocalState(builder, ducLocalState)

def ExportedDataStateAddDucGlobalState(builder, ducGlobalState):
    builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(ducGlobalState), 0)

def AddDucGlobalState(builder, ducGlobalState):
    ExportedDataStateAddDucGlobalState(builder, ducGlobalState)

def ExportedDataStateAddExternalFiles(builder, externalFiles):
    builder.PrependUOffsetTRelativeSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(externalFiles), 0)

def AddExternalFiles(builder, externalFiles):
    ExportedDataStateAddExternalFiles(builder, externalFiles)

def ExportedDataStateStartExternalFilesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartExternalFilesVector(builder, numElems):
    return ExportedDataStateStartExternalFilesVector(builder, numElems)

def ExportedDataStateAddVersionGraph(builder, versionGraph):
    builder.PrependUOffsetTRelativeSlot(15, flatbuffers.number_types.UOffsetTFlags.py_type(versionGraph), 0)

def AddVersionGraph(builder, versionGraph):
    ExportedDataStateAddVersionGraph(builder, versionGraph)

def ExportedDataStateEnd(builder):
    return builder.EndObject()

def End(builder):
    return ExportedDataStateEnd(builder)
