# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Duc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class IdentifiedSnapSettings(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = IdentifiedSnapSettings()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsIdentifiedSnapSettings(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def IdentifiedSnapSettingsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x55\x43\x5F", size_prefixed=size_prefixed)

    # IdentifiedSnapSettings
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IdentifiedSnapSettings
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Duc.Identifier import Identifier
            obj = Identifier()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # IdentifiedSnapSettings
    def Settings(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Duc.SnapSettings import SnapSettings
            obj = SnapSettings()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def IdentifiedSnapSettingsStart(builder):
    builder.StartObject(2)

def Start(builder):
    IdentifiedSnapSettingsStart(builder)

def IdentifiedSnapSettingsAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    IdentifiedSnapSettingsAddId(builder, id)

def IdentifiedSnapSettingsAddSettings(builder, settings):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(settings), 0)

def AddSettings(builder, settings):
    IdentifiedSnapSettingsAddSettings(builder, settings)

def IdentifiedSnapSettingsEnd(builder):
    return builder.EndObject()

def End(builder):
    return IdentifiedSnapSettingsEnd(builder)
