# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Duc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class IdentifiedLeaderStyle(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = IdentifiedLeaderStyle()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsIdentifiedLeaderStyle(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def IdentifiedLeaderStyleBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x55\x43\x5F", size_prefixed=size_prefixed)

    # IdentifiedLeaderStyle
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IdentifiedLeaderStyle
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Duc.Identifier import Identifier
            obj = Identifier()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # IdentifiedLeaderStyle
    def Style(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Duc.DucLeaderStyle import DucLeaderStyle
            obj = DucLeaderStyle()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def IdentifiedLeaderStyleStart(builder):
    builder.StartObject(2)

def Start(builder):
    IdentifiedLeaderStyleStart(builder)

def IdentifiedLeaderStyleAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    IdentifiedLeaderStyleAddId(builder, id)

def IdentifiedLeaderStyleAddStyle(builder, style):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(style), 0)

def AddStyle(builder, style):
    IdentifiedLeaderStyleAddStyle(builder, style)

def IdentifiedLeaderStyleEnd(builder):
    return builder.EndObject()

def End(builder):
    return IdentifiedLeaderStyleEnd(builder)
