# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Duc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class IdentifiedStackLikeStyle(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = IdentifiedStackLikeStyle()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsIdentifiedStackLikeStyle(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def IdentifiedStackLikeStyleBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x55\x43\x5F", size_prefixed=size_prefixed)

    # IdentifiedStackLikeStyle
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IdentifiedStackLikeStyle
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Duc.Identifier import Identifier
            obj = Identifier()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # IdentifiedStackLikeStyle
    def Style(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Duc.DucStackLikeStyles import DucStackLikeStyles
            obj = DucStackLikeStyles()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def IdentifiedStackLikeStyleStart(builder):
    builder.StartObject(2)

def Start(builder):
    IdentifiedStackLikeStyleStart(builder)

def IdentifiedStackLikeStyleAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    IdentifiedStackLikeStyleAddId(builder, id)

def IdentifiedStackLikeStyleAddStyle(builder, style):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(style), 0)

def AddStyle(builder, style):
    IdentifiedStackLikeStyleAddStyle(builder, style)

def IdentifiedStackLikeStyleEnd(builder):
    return builder.EndObject()

def End(builder):
    return IdentifiedStackLikeStyleEnd(builder)
