# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Duc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LinearUnitSystem(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LinearUnitSystem()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLinearUnitSystem(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def LinearUnitSystemBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x55\x43\x5F", size_prefixed=size_prefixed)

    # LinearUnitSystem
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LinearUnitSystem
    def Base(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Duc._UnitSystemBase import _UnitSystemBase
            obj = _UnitSystemBase()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # LinearUnitSystem
    def Format(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return None

    # LinearUnitSystem
    def DecimalSeparator(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return None

    # LinearUnitSystem
    def SuppressZeroFeet(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # LinearUnitSystem
    def SuppressZeroInches(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def LinearUnitSystemStart(builder):
    builder.StartObject(5)

def Start(builder):
    LinearUnitSystemStart(builder)

def LinearUnitSystemAddBase(builder, base):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(base), 0)

def AddBase(builder, base):
    LinearUnitSystemAddBase(builder, base)

def LinearUnitSystemAddFormat(builder, format):
    builder.PrependUint8Slot(1, format, None)

def AddFormat(builder, format):
    LinearUnitSystemAddFormat(builder, format)

def LinearUnitSystemAddDecimalSeparator(builder, decimalSeparator):
    builder.PrependUint8Slot(2, decimalSeparator, None)

def AddDecimalSeparator(builder, decimalSeparator):
    LinearUnitSystemAddDecimalSeparator(builder, decimalSeparator)

def LinearUnitSystemAddSuppressZeroFeet(builder, suppressZeroFeet):
    builder.PrependBoolSlot(3, suppressZeroFeet, 0)

def AddSuppressZeroFeet(builder, suppressZeroFeet):
    LinearUnitSystemAddSuppressZeroFeet(builder, suppressZeroFeet)

def LinearUnitSystemAddSuppressZeroInches(builder, suppressZeroInches):
    builder.PrependBoolSlot(4, suppressZeroInches, 0)

def AddSuppressZeroInches(builder, suppressZeroInches):
    LinearUnitSystemAddSuppressZeroInches(builder, suppressZeroInches)

def LinearUnitSystemEnd(builder):
    return builder.EndObject()

def End(builder):
    return LinearUnitSystemEnd(builder)
