# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Duc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PrimaryUnits(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PrimaryUnits()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPrimaryUnits(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def PrimaryUnitsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x55\x43\x5F", size_prefixed=size_prefixed)

    # PrimaryUnits
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PrimaryUnits
    def Linear(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Duc.LinearUnitSystem import LinearUnitSystem
            obj = LinearUnitSystem()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PrimaryUnits
    def Angular(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Duc.AngularUnitSystem import AngularUnitSystem
            obj = AngularUnitSystem()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def PrimaryUnitsStart(builder):
    builder.StartObject(2)

def Start(builder):
    PrimaryUnitsStart(builder)

def PrimaryUnitsAddLinear(builder, linear):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(linear), 0)

def AddLinear(builder, linear):
    PrimaryUnitsAddLinear(builder, linear)

def PrimaryUnitsAddAngular(builder, angular):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(angular), 0)

def AddAngular(builder, angular):
    PrimaryUnitsAddAngular(builder, angular)

def PrimaryUnitsEnd(builder):
    return builder.EndObject()

def End(builder):
    return PrimaryUnitsEnd(builder)
