# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Duc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SnapMarkerStyle(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SnapMarkerStyle()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSnapMarkerStyle(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SnapMarkerStyleBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x55\x43\x5F", size_prefixed=size_prefixed)

    # SnapMarkerStyle
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SnapMarkerStyle
    def Shape(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return None

    # SnapMarkerStyle
    def Color(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def SnapMarkerStyleStart(builder):
    builder.StartObject(2)

def Start(builder):
    SnapMarkerStyleStart(builder)

def SnapMarkerStyleAddShape(builder, shape):
    builder.PrependUint8Slot(0, shape, None)

def AddShape(builder, shape):
    SnapMarkerStyleAddShape(builder, shape)

def SnapMarkerStyleAddColor(builder, color):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(color), 0)

def AddColor(builder, color):
    SnapMarkerStyleAddColor(builder, color)

def SnapMarkerStyleEnd(builder):
    return builder.EndObject()

def End(builder):
    return SnapMarkerStyleEnd(builder)
