# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Duc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StandardOverrides(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StandardOverrides()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStandardOverrides(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def StandardOverridesBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x55\x43\x5F", size_prefixed=size_prefixed)

    # StandardOverrides
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StandardOverrides
    def MainScope(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # StandardOverrides
    def ElementsStrokeWidthOverride(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # StandardOverrides
    def CommonStyleId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # StandardOverrides
    def StackLikeStyleId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # StandardOverrides
    def TextStyleId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # StandardOverrides
    def DimensionStyleId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # StandardOverrides
    def LeaderStyleId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # StandardOverrides
    def FeatureControlFrameStyleId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # StandardOverrides
    def TableStyleId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # StandardOverrides
    def DocStyleId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # StandardOverrides
    def ViewportStyleId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # StandardOverrides
    def PlotStyleId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # StandardOverrides
    def HatchStyleId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # StandardOverrides
    def ActiveGridSettingsId(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # StandardOverrides
    def ActiveGridSettingsIdLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StandardOverrides
    def ActiveGridSettingsIdIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        return o == 0

    # StandardOverrides
    def ActiveSnapSettingsId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # StandardOverrides
    def DashLineOverride(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # StandardOverrides
    def UnitPrecision(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Duc.UnitPrecision import UnitPrecision
            obj = UnitPrecision()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def StandardOverridesStart(builder):
    builder.StartObject(17)

def Start(builder):
    StandardOverridesStart(builder)

def StandardOverridesAddMainScope(builder, mainScope):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(mainScope), 0)

def AddMainScope(builder, mainScope):
    StandardOverridesAddMainScope(builder, mainScope)

def StandardOverridesAddElementsStrokeWidthOverride(builder, elementsStrokeWidthOverride):
    builder.PrependFloat64Slot(1, elementsStrokeWidthOverride, 0.0)

def AddElementsStrokeWidthOverride(builder, elementsStrokeWidthOverride):
    StandardOverridesAddElementsStrokeWidthOverride(builder, elementsStrokeWidthOverride)

def StandardOverridesAddCommonStyleId(builder, commonStyleId):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(commonStyleId), 0)

def AddCommonStyleId(builder, commonStyleId):
    StandardOverridesAddCommonStyleId(builder, commonStyleId)

def StandardOverridesAddStackLikeStyleId(builder, stackLikeStyleId):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(stackLikeStyleId), 0)

def AddStackLikeStyleId(builder, stackLikeStyleId):
    StandardOverridesAddStackLikeStyleId(builder, stackLikeStyleId)

def StandardOverridesAddTextStyleId(builder, textStyleId):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(textStyleId), 0)

def AddTextStyleId(builder, textStyleId):
    StandardOverridesAddTextStyleId(builder, textStyleId)

def StandardOverridesAddDimensionStyleId(builder, dimensionStyleId):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(dimensionStyleId), 0)

def AddDimensionStyleId(builder, dimensionStyleId):
    StandardOverridesAddDimensionStyleId(builder, dimensionStyleId)

def StandardOverridesAddLeaderStyleId(builder, leaderStyleId):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(leaderStyleId), 0)

def AddLeaderStyleId(builder, leaderStyleId):
    StandardOverridesAddLeaderStyleId(builder, leaderStyleId)

def StandardOverridesAddFeatureControlFrameStyleId(builder, featureControlFrameStyleId):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(featureControlFrameStyleId), 0)

def AddFeatureControlFrameStyleId(builder, featureControlFrameStyleId):
    StandardOverridesAddFeatureControlFrameStyleId(builder, featureControlFrameStyleId)

def StandardOverridesAddTableStyleId(builder, tableStyleId):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(tableStyleId), 0)

def AddTableStyleId(builder, tableStyleId):
    StandardOverridesAddTableStyleId(builder, tableStyleId)

def StandardOverridesAddDocStyleId(builder, docStyleId):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(docStyleId), 0)

def AddDocStyleId(builder, docStyleId):
    StandardOverridesAddDocStyleId(builder, docStyleId)

def StandardOverridesAddViewportStyleId(builder, viewportStyleId):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(viewportStyleId), 0)

def AddViewportStyleId(builder, viewportStyleId):
    StandardOverridesAddViewportStyleId(builder, viewportStyleId)

def StandardOverridesAddPlotStyleId(builder, plotStyleId):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(plotStyleId), 0)

def AddPlotStyleId(builder, plotStyleId):
    StandardOverridesAddPlotStyleId(builder, plotStyleId)

def StandardOverridesAddHatchStyleId(builder, hatchStyleId):
    builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(hatchStyleId), 0)

def AddHatchStyleId(builder, hatchStyleId):
    StandardOverridesAddHatchStyleId(builder, hatchStyleId)

def StandardOverridesAddActiveGridSettingsId(builder, activeGridSettingsId):
    builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(activeGridSettingsId), 0)

def AddActiveGridSettingsId(builder, activeGridSettingsId):
    StandardOverridesAddActiveGridSettingsId(builder, activeGridSettingsId)

def StandardOverridesStartActiveGridSettingsIdVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartActiveGridSettingsIdVector(builder, numElems):
    return StandardOverridesStartActiveGridSettingsIdVector(builder, numElems)

def StandardOverridesAddActiveSnapSettingsId(builder, activeSnapSettingsId):
    builder.PrependUOffsetTRelativeSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(activeSnapSettingsId), 0)

def AddActiveSnapSettingsId(builder, activeSnapSettingsId):
    StandardOverridesAddActiveSnapSettingsId(builder, activeSnapSettingsId)

def StandardOverridesAddDashLineOverride(builder, dashLineOverride):
    builder.PrependUOffsetTRelativeSlot(15, flatbuffers.number_types.UOffsetTFlags.py_type(dashLineOverride), 0)

def AddDashLineOverride(builder, dashLineOverride):
    StandardOverridesAddDashLineOverride(builder, dashLineOverride)

def StandardOverridesAddUnitPrecision(builder, unitPrecision):
    builder.PrependUOffsetTRelativeSlot(16, flatbuffers.number_types.UOffsetTFlags.py_type(unitPrecision), 0)

def AddUnitPrecision(builder, unitPrecision):
    StandardOverridesAddUnitPrecision(builder, unitPrecision)

def StandardOverridesEnd(builder):
    return builder.EndObject()

def End(builder):
    return StandardOverridesEnd(builder)
