# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Duc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StandardUnits(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StandardUnits()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStandardUnits(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def StandardUnitsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x55\x43\x5F", size_prefixed=size_prefixed)

    # StandardUnits
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StandardUnits
    def PrimaryUnits(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Duc.PrimaryUnits import PrimaryUnits
            obj = PrimaryUnits()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StandardUnits
    def AlternateUnits(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Duc.AlternateUnits import AlternateUnits
            obj = AlternateUnits()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def StandardUnitsStart(builder):
    builder.StartObject(2)

def Start(builder):
    StandardUnitsStart(builder)

def StandardUnitsAddPrimaryUnits(builder, primaryUnits):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(primaryUnits), 0)

def AddPrimaryUnits(builder, primaryUnits):
    StandardUnitsAddPrimaryUnits(builder, primaryUnits)

def StandardUnitsAddAlternateUnits(builder, alternateUnits):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(alternateUnits), 0)

def AddAlternateUnits(builder, alternateUnits):
    StandardUnitsAddAlternateUnits(builder, alternateUnits)

def StandardUnitsEnd(builder):
    return builder.EndObject()

def End(builder):
    return StandardUnitsEnd(builder)
