# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Duc

class StrokeSidePreference(object):
    TOP = 10
    BOTTOM = 11
    LEFT = 12
    RIGHT = 13
    CUSTOM = 14
    ALL = 15
