# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Duc

class TEXT_FLOW_DIRECTION(object):
    LEFT_TO_RIGHT = 10
    RIGHT_TO_LEFT = 11
    TOP_TO_BOTTOM = 12
    BOTTOM_TO_TOP = 13
