# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Duc

class TOLERANCE_DISPLAY(object):
    NONE = 10
    SYMMETRICAL = 11
    DEVIATION = 12
    LIMITS = 13
    BASIC = 14
