// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum ANTI_ALIASING {
  MSAA_8 = 8,
  NONE = 10,
  ANALYTIC = 11,
  MSAA_16 = 16
}
