// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class DimensionValidationRules {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DimensionValidationRules {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDimensionValidationRules(bb:flatbuffers.ByteBuffer, obj?:DimensionValidationRules):DimensionValidationRules {
  return (obj || new DimensionValidationRules()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDimensionValidationRules(bb:flatbuffers.ByteBuffer, obj?:DimensionValidationRules):DimensionValidationRules {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DimensionValidationRules()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

minTextHeight():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

maxTextHeight():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

allowedPrecisions(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

allowedPrecisionsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

allowedPrecisionsArray():Int32Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Int32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startDimensionValidationRules(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addMinTextHeight(builder:flatbuffers.Builder, minTextHeight:number) {
  builder.addFieldFloat64(0, minTextHeight, 0.0);
}

static addMaxTextHeight(builder:flatbuffers.Builder, maxTextHeight:number) {
  builder.addFieldFloat64(1, maxTextHeight, 0.0);
}

static addAllowedPrecisions(builder:flatbuffers.Builder, allowedPrecisionsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, allowedPrecisionsOffset, 0);
}

static createAllowedPrecisionsVector(builder:flatbuffers.Builder, data:number[]|Int32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createAllowedPrecisionsVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createAllowedPrecisionsVector(builder:flatbuffers.Builder, data:number[]|Int32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]!);
  }
  return builder.endVector();
}

static startAllowedPrecisionsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endDimensionValidationRules(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createDimensionValidationRules(builder:flatbuffers.Builder, minTextHeight:number, maxTextHeight:number, allowedPrecisionsOffset:flatbuffers.Offset):flatbuffers.Offset {
  DimensionValidationRules.startDimensionValidationRules(builder);
  DimensionValidationRules.addMinTextHeight(builder, minTextHeight);
  DimensionValidationRules.addMaxTextHeight(builder, maxTextHeight);
  DimensionValidationRules.addAllowedPrecisions(builder, allowedPrecisionsOffset);
  return DimensionValidationRules.endDimensionValidationRules(builder);
}
}
