// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum DIMENSION_TEXT_ALIGNMENT {
  HORIZONTAL = 10,
  ALIGNED = 11,
  ISO_STANDARD = 12
}
