// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum DIMENSION_TEXT_POSITION {
  ABOVE = 10,
  CENTERED = 11,
  BELOW = 12
}
