// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum LINE_SPACING_TYPE {
  AT_LEAST = 10,
  EXACTLY = 11,
  MULTIPLE = 12
}
