// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum OBJECT_SNAP_MODE {
  ENDPOINT = 10,
  MIDPOINT = 11,
  CENTER = 12,
  QUADRANT = 13,
  INTERSECTION = 14,
  EXTENSION = 15,
  PERPENDICULAR = 16,
  TANGENT = 17,
  NEAREST = 18,
  NODE = 19,
  INSERT = 20,
  PARALLEL = 21,
  APPARENT = 22,
  FROM = 23,
  POINT_FILTER = 24,
  TEMPORARY = 25,
  BETWEEN_TWO_POINTS = 26,
  POINT_ON_CURVE = 27,
  GEOMETRIC = 28
}
