// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum STROKE_SIDE_PREFERENCE {
  TOP = 10,
  BOTTOM = 11,
  LEFT = 12,
  RIGHT = 13,
  CUSTOM = 14,
  ALL = 15
}
