[project]
name = "ducpy"
version = "0.0.0"
description = "The SDK for the Duc 2D CAD file format"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

license = { text = "MIT" }

authors = [
    { name = "Ducflair", email = "support@ducflair.com" }
]

classifiers = [
    "License :: OSI Approved :: MIT License",
]

[project.urls]
"Homepage" = "https://duc.ducflair.com"
"Source" = "https://github.com/ducflair/duc/tree/main/packages/duc-py"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"