[project]
name = "ducpy"
dynamic = ["version"]
description = "The library for the Duc 2D CAD file format"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flatbuffers>=25.2.10",
    "nanoid>=2.0.0",
]

license = { text = "MIT" }

authors = [
    { name = "Ducflair", email = "support@ducflair.com" },
    { name = "Jorge Soares" }
]

classifiers = [
    "License :: OSI Approved :: MIT License",
]

[project.urls]
"Homepage" = "https://duc.ducflair.com"
"Source" = "https://github.com/ducflair/duc/tree/main/packages/duc-py"
"Documentation" = "https://python.duc.ducflair.com"

[build-system]
requires = ["setuptools>=61.0.0", "setuptools_scm>=7.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "guess-next-dev"
local_scheme = "node-and-date"
fallback_version = "0.1.0"

[dependency-groups]
dev = [
    "furo>=2024.8.6",
    "sphinx>=8.1.3",
    "sphinx-autoapi>=3.6.0",
]
