import os
import re
from setuptools import setup

# Path to the schema file, relative to this setup.py file
# setup.py is in packages/duc-py/
# schema/duc.fbs is at the workspace root, so ../../schema/duc.fbs
SCHEMA_FILE_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', 'schema', 'duc.fbs')
# Path where _version.py will be written
VERSION_PY_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'src', 'ducpy', '_version.py')

def get_schema_version_from_fbs(fbs_file_path):
    try:
        with open(fbs_file_path, 'r') as f:
            first_line = f.readline()
            match = re.search(r'//\s*SCHEMA_VERSION\s*=\s*(\d+)', first_line)
            if match:
                return int(match.group(1))
    except FileNotFoundError:
        print(f"Warning: Schema file not found at {fbs_file_path}. Cannot parse version. Defaulting to 0.")
    except Exception as e:
        print(f"Warning: Could not parse schema version from {fbs_file_path}: {e}. Defaulting to 0.")
    return 0 # Default version if parsing fails or file not found

def generate_version_py():
    """Generates the _version.py file with DUC_SCHEMA_VERSION."""
    # Ensure the target directory for _version.py exists
    # This is important because setup.py might be executed before 
    # setuptools has created the src/ducpy directory structure in a build sandbox.
    os.makedirs(os.path.dirname(VERSION_PY_PATH), exist_ok=True)
    
    schema_version = get_schema_version_from_fbs(SCHEMA_FILE_PATH)
    print(f"Generating DUC schema version file at: {VERSION_PY_PATH} with version: {schema_version}")
    
    with open(VERSION_PY_PATH, 'w') as f:
        f.write(f'# This file is auto-generated by setup.py when the package is built.\n')
        f.write(f'# Do not edit this file manually.\n')
        f.write(f'DUC_SCHEMA_VERSION = {schema_version}\n')

# --- Main part of setup.py --- 

# Generate the version file when setup.py is processed by the build system.
generate_version_py()

# Minimal setup call.
# Most package metadata (name, version via setuptools-scm, etc.) and 
# package discovery are handled by pyproject.toml.
# This setup.py is present for compatibility and can be used for tasks 
# like C-extension building or build-time file generation if needed.
setup() 