// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { DucElement } from '../duc/duc-element.js';


export class DucGroupElement {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DucGroupElement {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDucGroupElement(bb:flatbuffers.ByteBuffer, obj?:DucGroupElement):DucGroupElement {
  return (obj || new DucGroupElement()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDucGroupElement(bb:flatbuffers.ByteBuffer, obj?:DucGroupElement):DucGroupElement {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DucGroupElement()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

base(obj?:DucElement):DucElement|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new DucElement()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

isCollapsed():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

groupIdRef():string|null
groupIdRef(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
groupIdRef(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startDucGroupElement(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addBase(builder:flatbuffers.Builder, baseOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, baseOffset, 0);
}

static addIsCollapsed(builder:flatbuffers.Builder, isCollapsed:boolean) {
  builder.addFieldInt8(1, +isCollapsed, +false);
}

static addGroupIdRef(builder:flatbuffers.Builder, groupIdRefOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, groupIdRefOffset, 0);
}

static endDucGroupElement(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createDucGroupElement(builder:flatbuffers.Builder, baseOffset:flatbuffers.Offset, isCollapsed:boolean, groupIdRefOffset:flatbuffers.Offset):flatbuffers.Offset {
  DucGroupElement.startDucGroupElement(builder);
  DucGroupElement.addBase(builder, baseOffset);
  DucGroupElement.addIsCollapsed(builder, isCollapsed);
  DucGroupElement.addGroupIdRef(builder, groupIdRefOffset);
  return DucGroupElement.endDucGroupElement(builder);
}
}
