import os
import re

from setuptools import setup

# Path to the schema file, relative to this setup.py file
# setup.py is in packages/ducpy/
# schema/duc.sql is at the workspace root, so ../../schema/duc.sql
SCHEMA_FILE_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', 'schema', 'duc.sql')
# Path where _version.py will be written
VERSION_PY_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'src', 'ducpy', '_version.py')

def get_schema_version_from_sql(sql_file_path):
    """Extract schema version from PRAGMA user_version in duc.sql.
    
    Format: user_version = 3000000 → version "3.0.0"
    Encoding: major * 1_000_000 + minor * 1_000 + patch
    """
    try:
        with open(sql_file_path, 'r') as f:
            content = f.read()
            match = re.search(r'PRAGMA\s+user_version\s*=\s*(\d+)', content)
            if match:
                version_int = int(match.group(1))
                major = version_int // 1_000_000
                minor = (version_int % 1_000_000) // 1_000
                patch = version_int % 1_000
                return f"{major}.{minor}.{patch}"
    except FileNotFoundError:
        return None
    except Exception as e:
        print(f"Warning: Could not parse schema version from {sql_file_path}: {e}. Defaulting to 0.0.0.")
    return "0.0.0"

def generate_version_py():
    """Generates the _version.py file with DUC_SCHEMA_VERSION."""
    schema_version = get_schema_version_from_sql(SCHEMA_FILE_PATH)

    if schema_version is not None:
        print(f"Generating DUC schema version file at: {VERSION_PY_PATH} with version: {schema_version}")
        os.makedirs(os.path.dirname(VERSION_PY_PATH), exist_ok=True)
        with open(VERSION_PY_PATH, 'w') as f:
            f.write(f'# This file is auto-generated by setup.py when the package is built.\n')
            f.write(f'# Do not edit this file manually.\n')
            f.write(f'DUC_SCHEMA_VERSION = "{schema_version}"\n')
    elif os.path.exists(VERSION_PY_PATH):
        print(f"DUC schema file not found. Using existing _version.py: {VERSION_PY_PATH}")
    else:
        print(f"DUC schema file not found and _version.py does not exist. Generating with default version 0.0.0 at: {VERSION_PY_PATH}")
        os.makedirs(os.path.dirname(VERSION_PY_PATH), exist_ok=True)
        with open(VERSION_PY_PATH, 'w') as f:
            f.write(f'# This file is auto-generated by setup.py (fallback).\n')
            f.write(f'DUC_SCHEMA_VERSION = "0.0.0"\n')

# --- Main part of setup.py --- 

# Generate the version file when setup.py is processed by the build system.
generate_version_py()

# Minimal setup call.
# Most package metadata (name, version via setuptools-scm, etc.) and 
# package discovery are handled by pyproject.toml.
# This setup.py is present for compatibility and can be used for tasks 
# like C-extension building or build-time file generation if needed.
setup() 