// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum DIMENSION_UNITS_FORMAT {
  DECIMAL = 10,
  ENGINEERING = 11,
  ARCHITECTURAL = 12,
  FRACTIONAL = 13,
  SCIENTIFIC = 14
}
