// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class DucPlotStyle {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DucPlotStyle {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDucPlotStyle(bb:flatbuffers.ByteBuffer, obj?:DucPlotStyle):DucPlotStyle {
  return (obj || new DucPlotStyle()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDucPlotStyle(bb:flatbuffers.ByteBuffer, obj?:DucPlotStyle):DucPlotStyle {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DucPlotStyle()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startDucPlotStyle(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static endDucPlotStyle(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createDucPlotStyle(builder:flatbuffers.Builder):flatbuffers.Offset {
  DucPlotStyle.startDucPlotStyle(builder);
  return DucPlotStyle.endDucPlotStyle(builder);
}
}
