// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class DucBlockCollectionEntry {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DucBlockCollectionEntry {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDucBlockCollectionEntry(bb:flatbuffers.ByteBuffer, obj?:DucBlockCollectionEntry):DucBlockCollectionEntry {
  return (obj || new DucBlockCollectionEntry()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDucBlockCollectionEntry(bb:flatbuffers.ByteBuffer, obj?:DucBlockCollectionEntry):DucBlockCollectionEntry {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DucBlockCollectionEntry()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

isCollection():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startDucBlockCollectionEntry(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addIsCollection(builder:flatbuffers.Builder, isCollection:boolean) {
  builder.addFieldInt8(1, +isCollection, +false);
}

static endDucBlockCollectionEntry(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createDucBlockCollectionEntry(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, isCollection:boolean):flatbuffers.Offset {
  DucBlockCollectionEntry.startDucBlockCollectionEntry(builder);
  DucBlockCollectionEntry.addId(builder, idOffset);
  DucBlockCollectionEntry.addIsCollection(builder, isCollection);
  return DucBlockCollectionEntry.endDucBlockCollectionEntry(builder);
}
}
