// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { _DucStackBase } from '../duc/duc-stack-base';


export class DucGroup {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DucGroup {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDucGroup(bb:flatbuffers.ByteBuffer, obj?:DucGroup):DucGroup {
  return (obj || new DucGroup()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDucGroup(bb:flatbuffers.ByteBuffer, obj?:DucGroup):DucGroup {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DucGroup()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

stackBase(obj?:_DucStackBase):_DucStackBase|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new _DucStackBase()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startDucGroup(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addStackBase(builder:flatbuffers.Builder, stackBaseOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, stackBaseOffset, 0);
}

static endDucGroup(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // id
  return offset;
}

}
