// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum GRID_DISPLAY_TYPE {
  LINES = 10,
  DOTS = 11,
  CROSSES = 12,
  ADAPTIVE = 13
}
