// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { DucTextStyle } from '../duc/duc-text-style';
import { Identifier } from '../duc/identifier';


export class IdentifiedTextStyle {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):IdentifiedTextStyle {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsIdentifiedTextStyle(bb:flatbuffers.ByteBuffer, obj?:IdentifiedTextStyle):IdentifiedTextStyle {
  return (obj || new IdentifiedTextStyle()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsIdentifiedTextStyle(bb:flatbuffers.ByteBuffer, obj?:IdentifiedTextStyle):IdentifiedTextStyle {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new IdentifiedTextStyle()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id(obj?:Identifier):Identifier|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Identifier()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

style(obj?:DucTextStyle):DucTextStyle|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new DucTextStyle()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startIdentifiedTextStyle(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addStyle(builder:flatbuffers.Builder, styleOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, styleOffset, 0);
}

static endIdentifiedTextStyle(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
