// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { DucView } from '../duc/duc-view';
import { Identifier } from '../duc/identifier';


export class IdentifiedView {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):IdentifiedView {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsIdentifiedView(bb:flatbuffers.ByteBuffer, obj?:IdentifiedView):IdentifiedView {
  return (obj || new IdentifiedView()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsIdentifiedView(bb:flatbuffers.ByteBuffer, obj?:IdentifiedView):IdentifiedView {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new IdentifiedView()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id(obj?:Identifier):Identifier|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Identifier()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

view(obj?:DucView):DucView|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new DucView()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startIdentifiedView(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addView(builder:flatbuffers.Builder, viewOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, viewOffset, 0);
}

static endIdentifiedView(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
