// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class LeaderTextBlockContent {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LeaderTextBlockContent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLeaderTextBlockContent(bb:flatbuffers.ByteBuffer, obj?:LeaderTextBlockContent):LeaderTextBlockContent {
  return (obj || new LeaderTextBlockContent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLeaderTextBlockContent(bb:flatbuffers.ByteBuffer, obj?:LeaderTextBlockContent):LeaderTextBlockContent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new LeaderTextBlockContent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

text():string|null
text(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
text(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startLeaderTextBlockContent(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addText(builder:flatbuffers.Builder, textOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, textOffset, 0);
}

static endLeaderTextBlockContent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createLeaderTextBlockContent(builder:flatbuffers.Builder, textOffset:flatbuffers.Offset):flatbuffers.Offset {
  LeaderTextBlockContent.startLeaderTextBlockContent(builder);
  LeaderTextBlockContent.addText(builder, textOffset);
  return LeaderTextBlockContent.endLeaderTextBlockContent(builder);
}
}
