// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { LeaderBlockContent } from '../duc/leader-block-content';
import { LeaderTextBlockContent } from '../duc/leader-text-block-content';


export enum LeaderContentData {
  NONE = 0,
  LeaderTextBlockContent = 1,
  LeaderBlockContent = 2
}

export function unionToLeaderContentData(
  type: LeaderContentData,
  accessor: (obj:LeaderBlockContent|LeaderTextBlockContent) => LeaderBlockContent|LeaderTextBlockContent|null
): LeaderBlockContent|LeaderTextBlockContent|null {
  switch(LeaderContentData[type]) {
    case 'NONE': return null; 
    case 'LeaderTextBlockContent': return accessor(new LeaderTextBlockContent())! as LeaderTextBlockContent;
    case 'LeaderBlockContent': return accessor(new LeaderBlockContent())! as LeaderBlockContent;
    default: return null;
  }
}

export function unionListToLeaderContentData(
  type: LeaderContentData, 
  accessor: (index: number, obj:LeaderBlockContent|LeaderTextBlockContent) => LeaderBlockContent|LeaderTextBlockContent|null, 
  index: number
): LeaderBlockContent|LeaderTextBlockContent|null {
  switch(LeaderContentData[type]) {
    case 'NONE': return null; 
    case 'LeaderTextBlockContent': return accessor(index, new LeaderTextBlockContent())! as LeaderTextBlockContent;
    case 'LeaderBlockContent': return accessor(index, new LeaderBlockContent())! as LeaderBlockContent;
    default: return null;
  }
}
