// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum PARAMETRIC_SOURCE_TYPE {
  CODE = 10,
  FILE = 11
}
