// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum PRUNING_LEVEL {
  CONSERVATIVE = 10,
  BALANCED = 20,
  AGGRESSIVE = 30
}
