// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { SNAP_OVERRIDE_BEHAVIOR } from '../duc/snap-override-behavior';


export class SnapOverride {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SnapOverride {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSnapOverride(bb:flatbuffers.ByteBuffer, obj?:SnapOverride):SnapOverride {
  return (obj || new SnapOverride()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSnapOverride(bb:flatbuffers.ByteBuffer, obj?:SnapOverride):SnapOverride {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SnapOverride()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

key():string|null
key(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
key(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

behavior():SNAP_OVERRIDE_BEHAVIOR|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : null;
}

static startSnapOverride(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addKey(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, keyOffset, 0);
}

static addBehavior(builder:flatbuffers.Builder, behavior:SNAP_OVERRIDE_BEHAVIOR) {
  builder.addFieldInt8(1, behavior, null);
}

static endSnapOverride(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSnapOverride(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset, behavior:SNAP_OVERRIDE_BEHAVIOR|null):flatbuffers.Offset {
  SnapOverride.startSnapOverride(builder);
  SnapOverride.addKey(builder, keyOffset);
  if (behavior !== null)
    SnapOverride.addBehavior(builder, behavior);
  return SnapOverride.endSnapOverride(builder);
}
}
