// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum STROKE_JOIN {
  MITER = 10,
  ROUND = 11,
  BEVEL = 12
}
