// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { UNIT_SYSTEM } from '../duc/unit-system';


export class _UnitSystemBase {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):_UnitSystemBase {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAs_UnitSystemBase(bb:flatbuffers.ByteBuffer, obj?:_UnitSystemBase):_UnitSystemBase {
  return (obj || new _UnitSystemBase()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAs_UnitSystemBase(bb:flatbuffers.ByteBuffer, obj?:_UnitSystemBase):_UnitSystemBase {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new _UnitSystemBase()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

system():UNIT_SYSTEM|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : null;
}

precision():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

suppressLeadingZeros():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

suppressTrailingZeros():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static start_UnitSystemBase(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addSystem(builder:flatbuffers.Builder, system:UNIT_SYSTEM) {
  builder.addFieldInt8(0, system, null);
}

static addPrecision(builder:flatbuffers.Builder, precision:number) {
  builder.addFieldInt32(1, precision, 0);
}

static addSuppressLeadingZeros(builder:flatbuffers.Builder, suppressLeadingZeros:boolean) {
  builder.addFieldInt8(2, +suppressLeadingZeros, +false);
}

static addSuppressTrailingZeros(builder:flatbuffers.Builder, suppressTrailingZeros:boolean) {
  builder.addFieldInt8(3, +suppressTrailingZeros, +false);
}

static end_UnitSystemBase(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static create_UnitSystemBase(builder:flatbuffers.Builder, system:UNIT_SYSTEM|null, precision:number, suppressLeadingZeros:boolean, suppressTrailingZeros:boolean):flatbuffers.Offset {
  _UnitSystemBase.start_UnitSystemBase(builder);
  if (system !== null)
    _UnitSystemBase.addSystem(builder, system);
  _UnitSystemBase.addPrecision(builder, precision);
  _UnitSystemBase.addSuppressLeadingZeros(builder, suppressLeadingZeros);
  _UnitSystemBase.addSuppressTrailingZeros(builder, suppressTrailingZeros);
  return _UnitSystemBase.end_UnitSystemBase(builder);
}
}
