// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class VersionGraphMetadata {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VersionGraphMetadata {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVersionGraphMetadata(bb:flatbuffers.ByteBuffer, obj?:VersionGraphMetadata):VersionGraphMetadata {
  return (obj || new VersionGraphMetadata()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVersionGraphMetadata(bb:flatbuffers.ByteBuffer, obj?:VersionGraphMetadata):VersionGraphMetadata {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VersionGraphMetadata()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

lastPruned():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

totalSize():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startVersionGraphMetadata(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addLastPruned(builder:flatbuffers.Builder, lastPruned:bigint) {
  builder.addFieldInt64(0, lastPruned, BigInt('0'));
}

static addTotalSize(builder:flatbuffers.Builder, totalSize:bigint) {
  builder.addFieldInt64(1, totalSize, BigInt('0'));
}

static endVersionGraphMetadata(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createVersionGraphMetadata(builder:flatbuffers.Builder, lastPruned:bigint, totalSize:bigint):flatbuffers.Offset {
  VersionGraphMetadata.startVersionGraphMetadata(builder);
  VersionGraphMetadata.addLastPruned(builder, lastPruned);
  VersionGraphMetadata.addTotalSize(builder, totalSize);
  return VersionGraphMetadata.endVersionGraphMetadata(builder);
}
}
