// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { DucElement } from '../duc/duc-element.js';


export class DucSelectionElement {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DucSelectionElement {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDucSelectionElement(bb:flatbuffers.ByteBuffer, obj?:DucSelectionElement):DucSelectionElement {
  return (obj || new DucSelectionElement()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDucSelectionElement(bb:flatbuffers.ByteBuffer, obj?:DucSelectionElement):DucSelectionElement {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DucSelectionElement()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

base(obj?:DucElement):DucElement|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new DucElement()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

type():string|null
type(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
type(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startDucSelectionElement(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addBase(builder:flatbuffers.Builder, baseOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, baseOffset, 0);
}

static addType(builder:flatbuffers.Builder, typeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, typeOffset, 0);
}

static endDucSelectionElement(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createDucSelectionElement(builder:flatbuffers.Builder, baseOffset:flatbuffers.Offset, typeOffset:flatbuffers.Offset):flatbuffers.Offset {
  DucSelectionElement.startDucSelectionElement(builder);
  DucSelectionElement.addBase(builder, baseOffset);
  DucSelectionElement.addType(builder, typeOffset);
  return DucSelectionElement.endDucSelectionElement(builder);
}
}
