name: Release ducjs

on:
  workflow_dispatch:
  push:
    branches: [main, next, dev]
    paths:
      - 'packages/ducjs/**'
      - 'package.json'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release_ducjs:
    runs-on: ubuntu-latest
    concurrency:
      group: release-ducjs
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
          persist-credentials: true
      - name: Set Git User
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"
      - name: Install deps
        run: bun install --frozen-lockfile

      - name: Build
        run: bun ducjs:build
      - name: Prepare workspace dependencies for publish
        run: node scripts/fix-workspace-deps.mjs packages/ducjs/package.json

      - name: Configure npm auth for publish
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup release environment
        id: setup-release-environment
        uses: ./.github/actions/simulate-main-environment
        with:
          current-branch: ${{ github.ref_name }}
          package-name: ducjs

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: ./packages/ducjs
        run: npx semantic-release ${{ steps.setup-release-environment.outputs.release-mode }}
