name: Release ducjs

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - next
    paths:
      - 'packages/ducjs/**'
      - 'turbo.json'
      - 'package.json'
  repository_dispatch:
    types: [trigger-ducjs-release]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release_ducjs:
    runs-on: ubuntu-latest
    concurrency:
      group: release-ducjs
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
          persist-credentials: true
      - name: Set Git User
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
      - name: Pull latest changes from origin/main
        run: git pull --rebase origin main
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Update npm
        run: npm install -g npm@latest
      - run: bun install
      - name: Build
        run: bun ducjs:build
      - name: Replace workspace dependencies (repo-wide, post-build)
        run: |
          find . -type f -name package.json \
            -not -path "./node_modules/*" \
            -not -path "./.git/*" \
            -print0 | xargs -0 -I {} sed -i -E 's/"workspace:[^\"]*"/"*"/g' {}
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_LEGACY_PEER_DEPS: "true"
          NPM_CONFIG_WORKSPACES: "false"
        run: npx semantic-release --ci
        working-directory: ./packages/ducjs
