name: Release duc2pdf

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - next
      - dev
    paths:
      - 'packages/ducpdf/src/duc2pdf/**'
      - 'package.json'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release_duc2pdf:
    runs-on: ubuntu-latest
    concurrency:
      group: release-duc2pdf
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
          persist-credentials: true
      - name: Set Git User
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"
      - name: Install deps
        run: bun install

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Update Rust toolchain
        run: rustup update stable
      - name: Install cargo-edit
        run: cargo install cargo-edit

      - name: Setup release environment
        id: setup-release-environment
        uses: ./.github/actions/simulate-main-environment
        with:
          current-branch: ${{ github.ref_name }}
          package-name: duc2pdf

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        working-directory: ./packages/ducpdf/src/duc2pdf
        run: npx semantic-release ${{ steps.setup-release-environment.outputs.release-mode }}
