name: Release Python

on:
  push:
    branches:
      - main
      - next
    paths:
      - 'packages/core/**'
      - 'packages/duc-py/**'
      - 'turbo.json'
      - 'package.json'
  repository_dispatch:
    types: [trigger-py-release]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release_duc_py:
    runs-on: ubuntu-latest
    concurrency:
      group: release-py
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          persist-credentials: true
      - name: Set Git User
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
      - name: Pull latest changes from origin/main
        run: git pull --rebase origin main
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: bun install
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install dependencies
        run: uv sync

        
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: bunx semantic-release --ci
        working-directory: ./packages/duc-py 