name: Release Rust

# Workflow temporarily disabled
run-name: "DISABLED: Release Rust"

on:
  workflow_dispatch:
    # Keeping only manual trigger option
  # Removed automatic triggers to disable workflow
  # push:
  #   branches:
  #     - main
  #     - next
  #   paths:
  #     - 'packages/duc-rs/**'
  #     - 'turbo.json'
  #     - 'package.json'
  # repository_dispatch:
  #   types: [trigger-rs-release]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release_duc_rs:
    runs-on: ubuntu-latest
    concurrency:
      group: release-rs
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          persist-credentials: true
      - name: Set Git User
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
      - name: Pull latest changes from origin/main
        run: git pull --rebase origin main
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Update Rust toolchain
        run: rustup update stable
      - name: Update npm
        run: npm install -g npm@latest
      - run: bun install
      - name: Build
        run: bun duc-rs:build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: npx semantic-release --ci
        working-directory: ./packages/duc-rs 