name: Release Python

on:
  push:
    branches:
      - main
      - next
    paths:
      - 'packages/ducpy/**'
      - 'turbo.json'
      - 'package.json'
  repository_dispatch:
    types: [trigger-py-release]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release_duc_py:
    runs-on: ubuntu-latest
    concurrency:
      group: release-py
      cancel-in-progress: false
    outputs:
      release_status: ${{ steps.release.outputs.status }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
          persist-credentials: true
      - name: Set Git User
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install Monorepo Dependencies
        run: bun install
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
        
      - name: Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          if bunx semantic-release --ci; then
            echo "status=success" >> $GITHUB_OUTPUT
          else
            echo "status=failure" >> $GITHUB_OUTPUT
          fi
        working-directory: ./packages/ducpy 