name: Release TypeScript

# Workflow temporarily disabled
run-name: "DISABLED: Release TypeScript"

on:
  workflow_dispatch:
    # Keeping only manual trigger option
  # Removed automatic triggers to disable workflow
  # push:
  #   branches:
  #     - main
  #     - next
  #   paths:
  #     - 'packages/ducjs/**'
  #     - 'turbo.json'
  #     - 'package.json'
  # repository_dispatch:
  #   types: [trigger-ts-release]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release_duc_ts:
    runs-on: ubuntu-latest
    concurrency:
      group: release-ts
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
          persist-credentials: true
      - name: Set Git User
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
      - name: Pull latest changes from origin/main
        run: git pull --rebase origin main
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Update npm
        run: npm install -g npm@latest
      - run: bun install
      - name: Replace workspace dependencies
        run: |
          sed -i 's/"workspace:\*"/"*"/g' packages/ducjs/package.json
      - name: Build
        run: bun ducjs:build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_LEGACY_PEER_DEPS: "true"
        run: npx semantic-release --ci
        working-directory: ./packages/ducjs 