name: Release Rust

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #     - next
  #   paths:
  #     - 'packages/ducrs/**'
  #     - 'turbo.json'
  #     - 'package.json'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release_duc_rs:
    runs-on: ubuntu-latest
    concurrency:
      group: release-ducrs
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
          persist-credentials: true
      - name: Set Git User
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Update Rust toolchain
        run: rustup update stable
      - name: Install cargo-edit
        run: cargo install cargo-edit

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: npx semantic-release --ci
        working-directory: ./packages/ducrs